"""The prose half of the target as data: sources, what the kit gets right and what changes, the
photographs-win disagreements, joints, fixings, meets, wear, what could not be settled. Read by
make_target.py. Evidence kinds: Read (printed in a source), Scaled (measured off a drawing or the
project's own files), Photo (measured on a photograph today, method and error given), Derived,
Judgement. Millimetres."""

SOURCES = [
    {"id": "P1", "what": "Leadenhall Market, a 360 degree HDRI (16384 x 8192), re-projected here to a level rectilinear elevation of the arcade's right-hand wall (yaw 90, focal 2400 px)",
     "url": "https://polyhaven.com/a/leadenhall_market; files: https://api.polyhaven.com/files/leadenhall_market (16k .hdr read 2026-10-09 from dl.polyhaven.org)",
     "read": "2026-10-09 (this cloud reached polyhaven.com and its file host)", "author": "Andreas Mischok", "licence": "CC0 (Poly Haven)",
     "taken": "2019-05-19", "shows": "heritage-restored Victorian covered market fronts (built c.1881, from memory, not checked): stone- or render-faced pilasters on stepped plinths, pier caps under a fascia, a deep cornice, heavy teal-painted window frames with a mid transom, a cast-iron ornament band over the head, cast-iron lattice stallrisers in frames, red double doors with a brass foot strip",
     "period": "NOT a 1990 object and not a provincial parade: a 2019 restoration of a London arcade (built c.1881, from memory). Used for proportions and the order of mouldings only, never for colour or wear. Why it still serves: it is the only reached photograph of a Victorian British shopfront in joinery and masonry at a measurable scale, and the parts it shows (plinth, shaft, necking, capital, fascia field, crown, sill, stallriser frame, transom, mullion, door) are the parts of a 1900-1935 parade front; the ratios between them are tested against the street's fixed numbers in section 4 of TARGET.md",
     "used": "Yes, measured: 44 rows and columns and one notice (photo_measurements.json), 8 joinery-only previews (the door's glass above its foot and everything seen through the shop window are filled flat; the house numerals are masked). The unmasked views carry real businesses' names and notices and were never saved into the repository",
     "scale": "fitted on ONE dimension: an A5 notice (148 x 210 mm) on the shop door's glass, 78.35 x 108.92 px (England's statutory no-smoking sign, whose 2007 minimum size was A5: from memory, legislation.gov.uk was unreached); each plane's own scale from its foot row: the pier's front 1.7282 mm a pixel, the window frame's (foot row 559.3) 1.8666, the door's (547.0) 1.9085; the window frame stands 332 and the door 433 behind the pier's face; the camera about 1.04 m above the footway"},
    {"id": "P2", "what": "Poly Haven CC0 roller-shutter models (rollershutter_window_01, _02, _03, rollershutter_door): glTF read today",
     "url": "https://polyhaven.com/models (files by https://api.polyhaven.com/files/<id>)", "read": "2026-10-09", "author": "MP (Poly Haven), published 2023-10-11", "licence": "CC0",
     "taken": "scanned or modelled 2023", "shows": "a steel hood, guide rails and a slatted curtain; hood depth 153, 168, 300 and 300 for curtains 1546, 1561, 1851 and 2400 high",
     "used": "Yes, for the roller-shutter box's depth and the rail width (alterations.roller_shutter); the form, not the date"},
    {"id": "G", "what": "the game's Rita front today: production/previews/rita-day-kit-2026-10-06.jpg (1600 x 900) and the kit sheet shopfront-kit-2026-10-06.jpg", "read": "2026-10-09", "author": "studio", "licence": "own",
     "shows": "the approved model: the plinth's top level with the stallriser, the side door cream with its knobs on its left edge, the shop door white with its lever on its left edge and its letter plate in the lock rail", "used": "Yes: the hinge sides, the plinth's line, the door's rails (measured on the 1600 x 900 frame; see game_today)"},
    {"id": "R", "what": "TARGET-REVIEW.md (the fresh reviewer's FAIL of the first try, 9 October 2026)", "read": "2026-10-09", "author": "a fresh target reviewer", "licence": "own",
     "shows": "eleven faults and their amendments, and the reviewer's own re-measuring of P1 on the 16k file (every stored row reproduced to 0.00 px)", "used": "Yes: every amendment applied except where this target shows a measurement against it (review_faults_answered)"},
    {"id": "K", "what": "the existing shopfront kit: production/art/shopfront-kit/README.md and tools/art-recipes/shopfront-kit/*.py (6 October 2026, by script)", "read": "2026-10-09", "author": "studio", "licence": "own",
     "shows": "the parts' sizes and profiles as built and the bay's datum", "used": "Yes: the starting point; every change is listed in kit_vs_target"},
    {"id": "F", "what": "production/research/shopfronts/FRONTAGE-2026-10-06.md (the project's earlier reading: council guides, Historic England entries, Building Conservation Directory, Ellis 1902 Modern Practical Joinery)", "read": "2026-10-09 (this file), its sources were read on the PC on 6 October",
     "author": "studio", "licence": "own", "shows": "anatomy, colours, wear, the four points where research differs from the spec", "used": "Yes, cited as the project's earlier reading, NOT re-read at source"},
    {"id": "W", "what": "production/research/shop-window-interiors/ (NOTE.md, FISHMONGER-2026-10-03.md ...), production/research/street-wear/PAINTED-FRONTS-2026-10-07.md, production/reference/photographs.md", "read": "2026-10-09",
     "author": "studio", "licence": "own", "shows": "what the period photographs establish: metal shopfronts beside older frontage, patterned tile stallrisers, recessed doorways with tiled thresholds; white tiles and slabs in fish shops; where a front wears", "used": "Yes, cited"},
    {"id": "S", "what": "SCENE-SLOTS.md, canon.md, RULINGS.md, production/specs/terrace-fronts.md, production/art/fascia-01/*, production/cloud-week/targets/fascia-signs/target.json, production/cloud-week/targets/front-door/target.json, tools/art-recipes/terrace-front.py (paints, refits, doors_on), production/previews/*.jpg (Rita's day and night, the kit sheet, the whole fronts, the Hook sheet)", "read": "2026-10-09",
     "author": "studio", "licence": "own", "shows": "the street's fixed numbers, the trades, the fascia's board and cornice, the F1 side door, the door ends, the paints", "used": "Yes"},
]

UNREACHED = [
    "Wikimedia Commons and Geograph (the period and modern photographs of British shopfronts; 403 or no route today)",
    "archive.org (Ellis, Modern Practical Joinery, 1902, and other books; no route)",
    "historicengland.org.uk (list entries 1488333, 1393627; no route)",
    "buildingconservation.com, the council guides (Brighton and Hove, Coventry, Westminster, RBKC, Cornwall, Richmond, Dover), Wikipedia, Gutenberg, HathiTrust, Google (no route)",
    "Flickr, Peter Marshall's Hull set, Picture Sheffield (the project's earlier reading of them is cited, not re-checked)",
]

WOULD_READ = [
    "Historic England 'Shopping Parades' (Introductions to Heritage Assets) and its Commerce and Exchange listing guide: the sections of surviving 1900-1935 consoles, cornices and pilasters, with dimensions",
    "Ellis, Modern Practical Joinery (1902), the shop-front plates: stile, mullion and transom sections, sill sections (the 'stout sill'), the cornice's limits in inches",
    "Geograph and Commons photographs, 1975-2000, of provincial British shopfronts: scrolled consoles and their leaves, 1970s aluminium fronts and their cover caps, roller-shutter boxes, plastic box signs over old fascias, recessed lobbies with tiled floors, whitewashed empty units (each with author, licence and date read on the file page)",
    "Peter Marshall's Hull photographs (R05, R09, West Dock Cafe, 1981) at the page: the metal front's section widths, the patterned tile's repeat",
    "A real surviving 1920s provincial front's measured drawing (a council's survey, or the Building Conservation Directory's 1994 'Retail Detail')",
    "Manufacturers' 1980s sections for aluminium shopfronts (the extrusion widths: 50 and 75 are Judgement here)",
]

KIT_VS_TARGET = {
    "pilaster": {
        "kit_gets_right": ["plinth, shaft, capital in that order, as every source and P1 show", "shaft 290 wide; 350 at the plinth and the capital's top, which makes the party-wall pair stand 0.70 m wide",
                           "panelled and fluted shafts as the period's timber types", "the plinth 600 high, level with the stallriser and the sill (Rita's line)", "a necking bead, a die with a raised tablet, a cap moulding",
                           "the kit's base ogee (60 high), which P1 confirms: it shows a moulding at the shaft's foot (made 15 proud, not the kit's 25, so that it stands on the cap's flat)", "the backing core, so no daylight shows between pilaster and frames"],
        "target_changes": [
            {"what": "shaft projection 100 -> 140, plinth projection 150 -> 180", "reason": "P1: the shaft's painted return beside the next surface is 117 mm (30.8 px at 1087 px off axis), a lower bound; the teal window frame beside it stands 276 behind the shaft's face. The first try read 117 as the whole relief and kept the frames at 95 and 100, so the shafts stood 10 to 15 mm proud of the frames (the review's fault 4). 140 keeps at least 40 in front of every frame beside it (the window jamb 95, the shop-door and F1 frames 100); the plinth goes with it, 40 in front of the shaft", "kind": "Photo (the bounds) and Judgement (the 140)"},
            {"what": "the plinth stays 600 (the first try's 800 withdrawn); a hollow-moulded head on the stepped variant", "reason": "P1's plinth is 1.33 times its sill (R1) and would break Rita's line, the plinth's top level with the stallriser in the approved model: Rita's line wins and the photograph's plinth is the unused variants.plinth_tall. P1's head moulding, which the first try dropped ('P1 shows none' was wrong), is adopted: a hollow (cavetto) 95 high and a band 21 high under the shaft", "kind": "Judgement (Rita's line) and Photo (the head)"},
            {"what": "the capital: die at d 144, a hollow flare from 144 to 172 over 90, abacus front 175, top 350 x 175", "reason": "P1's capital flares well out (its cream band reaches 57 px and its top slab 77 px beyond the shaft's edge); the first try's flare moved out only 14. The height 310 is Judgement: P1's 301 is an upper bound (the flare's and abacus's undersides add 30 to 60 mm)", "kind": "Photo and Judgement"},
            {"what": "a stepped plinth variant (render), a flush clad variant (Mickey's, as built, 140 proud like the shaft it cases)", "reason": "P1 shows four stepped members on the plinth; the Hook sheet and the street show Mickey's piers flat and plain", "kind": "Photo and Sheet"},
            {"what": "an optional three-boss die", "reason": "P1 shows the die with three roundels under a flared cap; the kit's cap is a straight moulding", "kind": "Photo"},
        ],
    },
    "console": {
        "kit_gets_right": ["240 wide x 550 high, z 2850 to 3400, centred on the pilaster, gap 0.0 mm", "the console standing on the capital's top"],
        "target_changes": [
            {"what": "the silhouette redrawn as a scroll in a 240 x 205 x 550 envelope (the built mesh's 180 deep is deepened by 25): a foot 240 x 172 on the capital's flat, a lower volute (eye d 158, z 48, outer radius 26, reaching d 184), a concave waist (narrowest d 140 at z 140), a stem swelling to d 150 at z 330, an upper volute (eye d 160, z 468, outer radius 45, the front reaching d 205 at z 468 and rolling back over the top through (160, 513)), a cap block 205 deep at z 528 to 550; grooves 8 inside the outline ending in eye bosses; the acanthus leaf kept, between z 150 and 420", "reason": "the first try's 'volute' was a groove on a plain corbel (the review's fault 5), and its scroll (waist 62, front 180) then stood BEHIND the fascia board's bed mould (132) for its lower 414 mm and set well back on the deeper capital (the re-review's fault): on all twenty consoles the board's ends showed beside the waist. Now the foot rises from the capital's front, the front is at least 140 at every height and the cornice's 215 nose oversails it by 10. NO photograph of a console was reached", "kind": "Judgement"},
                           {"what": "a plain block variant (the grocer, flaring from the 172 foot to 205) and an absent variant (the empty unit's left console)", "reason": "1930s fronts; fascia-01 spec", "kind": "Judgement"},
        ],
    },
    "fascia_board": {
        "kit_gets_right": ["the board between the consoles, 295 to 5705, 120 proud, z 2850 to 3400 (the fascia target's)"],
        "target_changes": [{"what": "a 40 high bed mould at the foot, 12 proud of the face", "reason": "P1 shows the fascia field framed by a mould where it meets the capital; the board's foot would otherwise be a bare box edge on the abacus", "kind": "Photo"},
                           {"what": "the face stays vertical", "reason": "P1 shows a vertical field; the guide's 'sloped slightly forward' (Coventry, the earlier reading) is a book and the photograph wins (D6)", "kind": "Photo"}],
    },
    "cornice": {
        "kit_gets_right": ["215 deep x 150 high x 5892 long, the drip groove outside the board's face, the wash, the lead apron (not geometry)"],
        "target_changes": [{"what": "the profile redrawn with a tall corona face (52, 0.35 of the height: Judgement), two fillets, a cyma reversa and a cap ovolo (19 points) inside the same envelope", "reason": "the built profile has 12 points and one curve; P1 shows a crown of several members", "kind": "Photo (the members) and Judgement (the sizes)"},
                           {"what": "each end closed by a mitred return of the full section, 215 deep back to the wall", "reason": "along the parade there are two exposed ends at every one of nine party walls, seen end-on from the street (the review's fault 8)", "kind": "Judgement"},
                           {"what": "the 150 height is KEPT: P1's crown is not measurable by this method", "reason": "the apparent crown is inflated by D.p/(D - p) for members above eye level and proud of the plane (130 to 270); the true crown is 170 to 300 (0.35 to 0.6 of the board); the fascia target fixes the cornice top at 3.55 and the hanging signs' brackets at 3.60 over it; an optional tall cornice (300) is recorded in variants with no photographic basis", "kind": "Not measurable, stated"}],
    },
    "sill": {
        "kit_gets_right": ["a weathered top falling to a rounded nose with a throat, 150 proud, 600 high"],
        "target_changes": [{"what": "50 thick -> 75 thick (z 525 to 600) with the throat 16 back from the nose", "reason": "Ellis (the earlier reading) calls the stallboard 'the stout sill' (no figure); P1's sill group is 80 px (142 mm) deep with a bead, a wide cove and a soffit; a 50 mm sill reads as a ledge; 75 is Judgement", "kind": "Read and Photo"}],
    },
    "stallriser": {
        "kit_gets_right": ["panelled (raised and fielded, 3 panels) and glazed-tile variants, 600 high, face 125", "the plinth, skirting 120"],
        "target_changes": [{"what": "six more variants: square tile, patterned tile, glass slab, render, boarded, and a grille (available, unused)", "reason": "the ten fronts need them: P1 shows a framed grille panel, and the earlier reading of R05 a patterned tile", "kind": "Judgement and Photo"}],
    },
    "window_frame": {
        "kit_gets_right": ["sill 600 to head 2850, transom 2400 to 2480, mullions in front of the glass, glass 30 in front of the wall", "toplights in a shallow row", "the transom's weathered top, drip and nose (a book detail, also seen in P1)"],
        "target_changes": [{"what": "mullion 55 -> 70 wide, front at 92 (62 in front of the glass)", "reason": "P1's mullion is 92 px wide (172 mm at the window frame's own plane, 0.15 of the light), the kit's 0.05. The guides' 40 to 70 mm is a projection. Not followed in full (D5)", "kind": "Photo, partly followed"},
                           {"what": "a 25 mm seat on the sill (the first try's 90 mm bottom rail withdrawn)", "reason": "in P1 the sill group's top is the glazing rebate's foot: the lights stand on the sill; with the shop door's glass level with the sill (D2) the window's glass should start within 25 of it", "kind": "Photo and Judgement"},
                           {"what": "four more types: T2, M1, M2", "reason": "the street needs timber, aluminium and 1930s bronze fronts", "kind": "Judgement"}],
    },
    "shop_door": {
        "kit_gets_right": ["leaf 900 x 2040, frame 1006 wide, 100 deep, kick plate, lever handles, three hinges, terrazzo threshold"],
        "target_changes": [{"what": "glazed from 1000 -> 600, level with the sill's top", "reason": "P1's door glass starts 0.304 of its leaf up (798 mm of 2624, 620 on a 2040 leaf), within 46 mm of its window's sill (the first try's snap landed inside the dark glass, row 95.7 with a strength of 1.5; the glass foot is row 128.9, strength 12.2); Coventry (the earlier reading) says the door's bottom panel is the stallriser's height. The scene's 1.0 is a trade-standard guess. The door's lower portion is then bottom rail 230, panel 260, lock rail 110", "kind": "Photo and Read"},
                           {"what": "the letter plate 250 x 40 centred at z 545 in the lock rail (490 to 600), not at 800 in the glass", "reason": "with the glass from 600 the first try's z 800 stood in the glass; the game's Rita door has the plate in the lock rail", "kind": "Judgement and Sheet"},
                           {"what": "a 30 high brass foot strip across the leaf's foot (the lowest 30 of the kick plate on T1)", "reason": "P1's door foot carries one (15 px, 29 mm); the game's Rita door a 170 plate: one piece, the strip its worn foot", "kind": "Photo"},
                           {"what": "a hinge side per shop: the shop door hinged on the window side, the side door on the shop-door side", "reason": "taken from Rita's front in the game today: both levers/knobs on the leaves' left edges; the first try's drawing put every lever on the right", "kind": "Sheet (the game frame)"},
                           {"what": "aluminium and bronze door variants", "reason": "the refits", "kind": "Judgement"}],
    },
    "side_door": {"kit_gets_right": ["the 944 slot, the fielded panel over the transom"], "target_changes": [{"what": "the leaf is the front-door family's F1 (not re-targeted); its hinge side follows Rita's", "reason": "the brief; the game frame", "kind": "Read and Sheet"}]},
}

DISAGREEMENTS = [
    {"id": "D1", "element": "plinth height", "book_or_scene": "kit, scene and Rita's front, the approved model: the plinth's top is level with the stallriser, 600", "photograph": "P1: plinth top 1123 mm at its own plane, 1.33 times its sill's top (844) and 0.228 of its front's height; scaled to the street's 3.55 m that is 811", "chosen": "600: Rita's window is Jafar's model and a market-hall pier must not break its line. The photograph's plinth is kept as the unused variants.plinth_tall (800, the review's profile points); P1's head moulding (a hollow and a band) is adopted at 600", "photo_followed": False},
    {"id": "D2", "element": "shop door glazed from", "book_or_scene": "scene C8: 1.0 m; the game's Rita door today", "photograph": "P1: the glass foot (row 128.9) is 0.304 of the leaf (798 of 2624 mm; 620 on a 2040 leaf), 46 mm below its window's sill; Coventry (the earlier reading): the door's bottom panel is the stallriser's height", "chosen": "600, level with the sill, as P1 shows and as Coventry says; the scene's 1.0 loses", "photo_followed": True},
    {"id": "D3", "element": "shaft projection", "book_or_scene": "scene: 100; the first try's 110", "photograph": "P1: the painted return beside the next surface is 117 (a lower bound, 30.8 px at 1087 px off axis) and the teal window frame stands 276 behind the shaft's face", "chosen": "140: at least 40 in front of every frame beside it (95, 100, 100); the scene's 0.10 loses", "photo_followed": True},
    {"id": "D4", "element": "capital height", "book_or_scene": "kit: 330", "photograph": "P1: at most 301 (an upper bound: the flare's and abacus's undersides add 30 to 60 mm to the 174 px)", "chosen": "310 (Judgement: the capital carries the console's toe and the board's foot)", "photo_followed": False},
    {"id": "D5", "element": "mullion width", "book_or_scene": "kit 55; Cornwall guide: projecting 40-70 from the glass (a projection, not a width)", "photograph": "P1: 172 mm (92.1 px at the window frame's own plane, 1.8666 mm a pixel), 0.15 of a 1.0 m light", "chosen": "70 (T1), 80 (T2): the photograph is a heavy plate-glass arcade front; not followed in full. If the reviewer reads the photograph as authoritative, 100 to 120 is the next step", "photo_followed": False},
    {"id": "D6", "element": "fascia face", "book_or_scene": "Coventry 2014 (the earlier reading): sloped slightly forward", "photograph": "P1: vertical", "chosen": "vertical", "photo_followed": True},
    {"id": "D7", "element": "cornice height", "book_or_scene": "fascia-01: 150; Ellis (the earlier reading, in the London rules of about 1902): a cornice may PROJECT 13 in (330) in a street up to 30 ft wide and 18 in in a wider one (a limit on projection, not height; ours projects 215)", "photograph": "P1: NOT measurable by this method: the apparent crown (433 at the pilaster plane) is inflated by D.p/(D - p) for members above eye level and proud of the plane (130 to 270); the true crown is 170 to 300, 0.35 to 0.6 of the board", "chosen": "150 kept (the fixed envelope); the corona's 0.35 of the height is Judgement; variant 'tall' 300 offered with no photographic basis", "photo_followed": False},
    {"id": "D8", "element": "sill thickness", "book_or_scene": "kit: 50", "photograph": "P1: the sill group 140 deep with a bead, cove and soffit; Ellis: stout sill", "chosen": "75", "photo_followed": True},
    {"id": "D9", "element": "stallriser height", "book_or_scene": "scene 600; guides 400 to 700", "photograph": "P1: sill top 844 at the window frame's own plane, 0.172 of the front's height (0.61 m at 3.55)", "chosen": "600 (no disagreement)", "photo_followed": True},
    {"id": "D10", "element": "the pilasters in pairs at the party wall", "book_or_scene": "scene: a pier at every bay edge (two 0.35 piers butt)", "photograph": "P1 has single piers between shops", "chosen": "pairs kept: the scene is a fixed fact of the street and a parade of separately owned shops did have a pilaster each; they butt with a painted vertical joint", "photo_followed": False},
    {"id": "D11", "element": "the scrolled console", "book_or_scene": "the brief and the earlier reading: consoles are scrolled brackets", "photograph": "P1's pier caps are straight stepped blocks, not scrolls: the photograph does not show the part", "chosen": "a two-volute scroll in a 240 x 205 x 550 envelope by Judgement (the built mesh's 180 stood behind the board); stated as not established by a photograph, and the first piece to check against a reached one", "photo_followed": False},
    {"id": "D12", "element": "the side door's hinge side in Rita's front", "book_or_scene": "the review: the side door's knob is on its right, so it is hinged on the pier side and F1 is used as drawn where the door end is the viewer's left", "photograph": "the game frame (not a photograph): the side door's leaf spans x 215.7 to 397.3 and its knobs stand at x 225.7 and 220.0, in the leaf's left tenth; the shop door's lever (x 446.7 to 475) is left of its glass (x 457.7 to 604)", "chosen": "both leaves hinged on the viewer's right in Rita's: the side door on the shop-door side with its knob on the pier side; F1 is mirrored where the door end is the viewer's left; the shop door's side agrees with the review", "photo_followed": True},
]

JOINTS = [
    {"between": "pilaster shaft and plinth", "how": "panel and flute: the shaft stands on the plinth cap's flat with the kit's base ogee made 15 proud of the shaft's face (front d 155, on the flat; the kit's 25 would float over the weathering), 60 high, z 600 to 660, returned on both sides; render: the hollow (cavetto) head and its band take the shaft directly, the band 8 in front of the shaft's face (P1 shows a moulding at the shaft's foot; the first try's 'P1 shows none' was wrong). A 3 mm shadow line at the foot where paint has filled the gap"},
    {"between": "pilaster pair at the party wall", "how": "two 350 piers butt at u = 0 / 6000: a vertical joint 2 mm wide, paint-cracked, 0 to 2850; capitals touch; plinth caps touch. The shafts (290 in a 350 slot) stand 60 apart across the party line. The D5 downpipe (68 across, axis 94 from the wall, so d 60 to 128) stands in that gap, 12 behind the shafts' faces (140); the plinths and the capitals are notched for it by a chase 76 wide (u +-38) from d 50 to their fronts (z 0 to 600 and 2540 to 2850); the cornice stops 54 short of each side and the consoles stand 110 apart, so the pipe passes all the way up"},
    {"between": "pilaster and the frames beside it", "how": "the shaft's face (140) stands 45 in front of the window jamb (95) and 40 in front of the shop-door frame and the F1 frame (100); the backing core, painted the pier's colour, makes the return between them, so no daylight and no unpainted edge shows (check PIL-15: at least 40 in front of every frame)"},
    {"between": "console and capital", "how": "the foot 240 x 172 stands on the abacus's top at z 2850, centred on u 175 / 5825; 0.0 mm gap; the capital's top is 350 x 175 (its flat reaches d 172, an ovolo rounds the last 3), so the console rises from the capital's front; two 12 mm hardwood dowels 40 deep from the foot into the capital; two M10 coach screws through the console's back into the wall plate (hidden); the lower volute (d 184) overhangs the capital's front by 9"},
    {"between": "fascia board and console", "how": "the board's ends are let into the consoles' inner sides by a 12 mm rebate; the console's front is at least d 140 at every height, in front of the board's face (120) and its bed mould (132), so no board end or mould stands proud of the console; a 2 mm paint-filled line shows on each side (check CON-09)"},
    {"between": "fascia board and capital", "how": "the board's foot rests on the abacus for 55 (u 295 to 350 and 5650 to 5705); the capital's top reaches d 172 to 175, so the board (face d 120) and its bed mould (front 132) stand wholly on it, the mould's front 43 behind the capital's front"},
    {"between": "cornice and fascia", "how": "the soffit lies on the board's top and the consoles' tops at z 3400 with 0 gap; the drip groove at d 155 to 175 lies outside the board's face (120) by 35; the nose (215) oversails the board by 95 and the console (205) by 10; a lead apron over the wash, 100 up the wall"},
    {"between": "cornice and the party wall", "how": "the cornice stops 54 short of each party line (u 54 and 5946) leaving a 108 gap between neighbours for the downpipe; each end is closed by a mitred return of the full 19-point section back to the wall, 215 deep: a 45 degree mitre in plan from the wall at u 269 / 5731 to the nose corner at u 54 / 5946, glued with a loose tongue, the return's back screwed to the wall plate; the lead apron is dressed down over the return with a 25 upstand"},
    {"between": "window frame and sill", "how": "the 25 mm seat (z 600 to 625) stands on the sill's flat bed (d 0 to 60), screwed from below through the sill; a mastic line at the junction (1 mm); the glass sits in the rebate from 625"},
    {"between": "window frame and pilaster / door frames", "how": "the end jambs (50 x 95) close against the pilaster's backing core and the door frames' jambs; a 3 mm paint joint; no daylight; the jamb's face is 45 behind the shaft's"},
    {"between": "transom and jambs", "how": "the transom is housed 10 mm into each jamb with a stub tenon, drawbore-pegged inside; outside only a 1 mm line shows"},
    {"between": "mullions and transom/seat", "how": "mortice and tenon, 25 mm tenon, wedged; end grain not visible after painting; the mullion stops at the transom (z 2400) and the toplight bars start on it"},
    {"between": "stallriser and plinths", "how": "the stallriser's ends butt the plinths' sides; the plinth is 55 proud of the stallriser face and 30 of the sill's nose; a 2 mm line"},
    {"between": "sill and plinth", "how": "the sill's ends are cut round the plinth's cap and stop 3 short of the plinth's side"},
    {"between": "shop door frame and threshold", "how": "the terrazzo threshold (25 high) runs the frame's width; the leaf clears it by 3 mm over a brass foot strip"},
    {"between": "shop door glass and the sill", "how": "the door's glass foot (z 600, the lock rail's top) runs on as one line with the window sill's top (600) along the front: the lock rail 490 to 600 carries the letter plate (z 545) and the lever stands above it at z 1000"},
    {"between": "side-door slot and the shop door frame", "how": "the F1 frame's jamb and the shop door's jamb stand 3 apart under a common head strip; the transom runs across both"},
    {"between": "box sign / flat panel and the old board", "how": "stands on the board at the fascia target's outer rectangle; eight pan-head screws; the cornice's soffit clears its top by 35"},
    {"between": "roller-shutter hood, rails and curtain", "how": "the hood (300 high, 210 deep, z 2550 to 2850, u 350 to 4706) is SET INTO the toplight zone and screwed to the fascia's rail: the head, the toplight bars and the toplight glass are cut away at z 2550 behind it, so it shares no space with them, and 70 of the toplights shows below; the guide rails (50 wide, 40 deep, d 150 to 190, z 0 to 2550) stand on steel spacer brackets bolted through the frames into the pilaster's core; the curtain runs in one plane at d 170, 20 clear of the sill's nose, across window and door to the footway"},
]

FIXINGS = [
    {"part": "pilaster", "fixing": "100 mm cut nails or No. 10 screws through the core into wall plugs at 600 pitch; heads punched and stopped; after repainting they show as faint round dots 4 mm across at 600 in two lines 40 from the edges (Judgement)"},
    {"part": "console", "fixing": "two 12 mm dowels and two M10 coach screws, hidden; a rust bleed 20 mm long under each screw hole on the shaded side after 70 years (Judgement)"},
    {"part": "fascia board", "fixing": "50 mm cut nails at 300 along the top and bottom edges into the rails; heads stopped; the fascia target puts ten pin holes along a removed sign"},
    {"part": "cornice", "fixing": "75 mm brass or galvanised screws through the soffit into the wall plate at 450, pellet-plugged and painted; the mitred returns glued and tongued, screwed through their backs into the wall plate; the lead is fixed with copper clout nails at 25 along its upper edge, pointed into the brick"},
    {"part": "window frame", "fixing": "100 mm screws through the end jambs into the pilaster core at 450; the sill screwed down through its bed (No. 12 at 450, plugged); beads on brass round-head screws at 250 (T1), snap-in (M1)"},
    {"part": "stallriser", "fixing": "panels screwed from behind into the sill and the plinth; tile on a cement-sand screed on battens; slabs on a stainless or brass clip at 400"},
    {"part": "doors", "fixing": "three 100 x 75 butt hinges, 6 No. 8 screws each, on the window side of the shop door and the shop-door side of the side door; a mortice lock and a rim night latch; the kick plate with 8 brass screws; the F1 door as its own target"},
    {"part": "seen on P1, not adopted", "fixing": "P1's pilaster shows two small iron hooks on its side return (a later fixing for a flag or a banner) and a bracket-like fixing on the shaft's right edge; the 1990 street hangs its signs from brackets on the brick above the cornice (the fascia target), so none is placed on the shafts"},
    {"part": "roller-shutter box", "fixing": "four M8 bolts per rail through the frame into the pilaster core, the rails standing out on steel spacer brackets (d 150 to 190), bolt heads visible; the hood, set into the toplight zone with the head, bars and glass cut away behind it, on steel angle brackets screwed into the fascia's rail, 600 pitch; rivets on the end caps"},
]

WEAR = {
    "photo_P1_2019": "Fine white scuffs on the red plinth up to about 0.4 m, chipped arrises at the cap's edges, the sill group's bead and cove carrying bright worn lines where paint has worn through, the brass foot strip worn, a repaired patch on the plinth's foot. P1 is a 2019 restoration in fresh gloss: it shows what wear looks like on a part, not what 1990 looked like",
    "earlier_notes_1990": "FRONTAGE-2026-10-06.md section 3 and PAINTED-FRONTS-2026-10-07.md: paint failing at the sill and the joints, pilaster feet rotting and splashed, stallrisers stained by pavement splash up to 0.45 m, door bottoms decaying, fascias rotting from their backs; the wear layer's work (a height gradient and noise in the material), not the meshes'. The wear target (production/cloud-week/targets/wear) governs it",
    "geometry_wear_in_this_target": ["arris radius 1 to 2.5 mm on every timber edge by repainting", "a 3 mm V of rot at the pilaster foot's front arris on the oldest fronts (empty unit, ironmonger)",
                                     "the empty unit's console stub", "cracks 0.5 x 80 in a tile or slab at doors on the tiled fronts (tile and slab stallrisers)",
                                     "aluminium: pits and a white corrosion bloom at the foot, 40 to 60 high"],
}

COULD_NOT_SETTLE = [
    "The scrolled console and its leaf: no photograph at all; the console is the FIRST piece to check against a reached photograph. The silhouette is a 240 x 205 x 550 scroll (the built mesh's 180 deep stood behind the board) with two volutes, a waist no narrower than d 140 and a cap block by Judgement; the grooves, bosses and the leaf are Judgement",
    "No photograph of a provincial 1900-1935 shopfront was reached (Wikimedia, Geograph, Flickr, archive.org and the council guides all refused; the other British street HDRIs on Poly Haven, urban_street_01 to 04 and bethnal_green_entrance, show no shopfront). P1 is a London arcade (c.1881, from memory) restored in 2019: it governs proportions near eye level (the plinth against the sill, the door glass against the sill, the shaft width, the foot strip, the order of members); it does not govern timber plinth heights on provincial parades, 1970s aluminium sections, a provincial fascia's slope, panel layouts, fluting, console scrolls or leaves, roller-shutter boxes, box signs, lobbies or whitewashed empty units. Those rest on the earlier notes (cited, not re-read) and Judgement, each marked",
    "P1's plinth (1.33 times its sill) against Rita's line (the plinth level with the stallriser): this target keeps Rita's 600 on every front and offers 800 only as variants.plinth_tall. It rests on one market-hall pier and the approved model; if the plan owner wants the photograph's plinth the variant is ready, a visible change to Jafar's model",
    "The 1960s-80s aluminium front's sections (50 x 75, cover caps, mastic joints): Judgement; R05 and R09 only say such fronts existed",
    "Absolute scale of P1: the A5 notice is assumed to be A5 (148 x 210; England's statutory no-smoking sign, whose 2007 minimum size was A5: from memory, unchecked); each plane's scale follows from its foot row at the same footway level. The scale is +-8 per cent and every Leadenhall millimetre carries it. Ratios do not",
    "Mickey's door: mickeys-office.json puts it at street x 4.65 (the rank spot, the unlock distance); the kit's slots put the shop door's centre at x 4.797, 147 mm farther from the party wall, because the side door slot is 944 and the shop door slot 1006. Rita's front already stands so. A town question (move the door x or narrow the side door's slot)",
    "The fascia target puts a street number on every side door's fanlight (the grocer's at x 38.18); the street recipe and terrace-fronts.md give the grocer no side door (BAY_WITHOUT_SIDE_DOOR = 5). This target follows the recipe; the number belongs on the shop door's fanlight (x 38.147). A fascias question",
    "The ironmonger and the launderette: the street recipe has no metal refit for the laundry's bay (SHOPFRONT_REFITS has no east_parade 4) and makes the ironmonger one (west_north 1); this target gives the laundry an aluminium refit with a box sign (the fascia target's box) and keeps the ironmonger timber to suit its traditional board. Both depart from the recipe; a town or art question",
    "The launderette's vent pipe: terrace-fronts.md runs a vent pipe through the fascia band, which would collide with the laundry's box sign (5200 x 480 x 150); a fascias or town question, not settled here",
    "Twelve fronts or ten: RULINGS 2 Oct counts twelve; the scene has ten shop bays (six east, the chandler, three west). Ten are tabled. A coin shop at x 39 (hook-cast) is not in the scene",
    "The Hook sheet shows a recessed Mickey's door and an angled display bay at the corner; the street's Mickey's is a flat front with its door and room walked in the game. This target keeps it flush (as built) and gives the recess to the grocer and the launderette",
    "The party-wall downpipe: the 6 October note says it goes 'inside the hollow pilaster'; at the roofline's 94 mm offset it cannot (the shaft is 140 proud and the pipe's front stands at 128). This target leaves the pipe where the roofline has it, in the 60 mm gap between the two shafts and a 76 mm chase through the plinths and capitals; the pipe's front is now 12 behind the shafts' faces; the roofline owner may prefer to move the pipe back",
    "The door handing: the street recipe places the kit's door by translation only, so every bay today carries Rita's handing (levers on the viewer's left). This target gives the five mirrored fronts (Mickey's, fish, empty unit, ironmonger, newsagent) the mirror: hinged on the window side, the lever on the other edge. If the builder keeps the street's handing the hinge/lever check DOR-07 reports those five",
    "The roller shutter's hood depth (210) and the curtain plane (170) are the reviewer's Judgement fixed by clearing the frames; the Poly Haven scans have 150 to 300 deep hoods",
    "Texture size, UVs, material slots and vertex-colour masks are the builder's (the kit's method stands); nothing here changes them",
    "Nobody has looked at these parts at the game's exposure and internal resolution; what is visible at 8 m is not judged",
]


# which numbers rest on what (the brief: photographs measured today, the earlier notes, judgement)
EVIDENCE = {
    "pilaster": {"photo_today": ["shaft 290 wide (290.1 +-8 per cent at the measured scale)", "shaft relief beside the next surface: 117 (painted return, a lower bound) to 276 (the teal frame): 140 sits inside", "the stepped plinth's members (tops at 0.63 / 0.79 / 0.85 of its height) and its hollow-moulded head with a band", "a moulding at the shaft's foot", "the capital's flare (cream band 57 px and top slab 77 px beyond the shaft's edge)", "the capital's height as an upper bound (301)", "the three-boss die (optional)", "the plinth's top against its sill (1.33: NOT followed, Rita's line)"],
                 "earlier_notes": ["panelled and fluted timber types; plinth at least the stallriser's height (RBKC); 0.35 slot and 0.10 proud (the scene)", "the pairs at the party wall (scene, DOWNPIPE note)", "the kit's base ogee"],
                 "judgement": ["the shaft's 140 and the plinth's 180 (the relief rule), the capital's 310 and its 175 top", "every moulding's profile (astragal r 12, flare hollow, ovolo), the sunk panel's depth 12 and bead 10, the flutes' 12, the stepped plinth's lower blocks at 600 (360 / 450 / 484), the clad variant's sheets", "the downpipe chase"]},
    "console": {"photo_today": [], "earlier_notes": ["240 wide x 550 high and a toe on the capital (the built mesh, fascia-01; its 180 depth is deepened to 205)", "consoles at each end of the fascia on the capitals (FRONTAGE: CV, KC, CW)"],
                "judgement": ["the two-volute outline, the waist, the grooves, the bosses, the leaf, the block variant", "NO PHOTOGRAPH of a console was reached: the first piece to check"]},
    "fascia_board": {"photo_today": ["vertical face; a field with a mould where it meets the capital"], "earlier_notes": ["5410 x 550 x 120 (fascia target, kit)", "not more than 600 and a fifth of the front (CV, RI)"], "judgement": ["the bed mould's 40 x 12", "board thickness 25"]},
    "cornice": {"photo_today": ["a crown of several members (cyma, corona, fillets); its height is NOT measurable by this method (170 to 300)"], "earlier_notes": ["215 x 150 x 5892, the drip groove, the 27 degree wash, the lead (fascia-01)"], "judgement": ["the 19-point profile's member sizes", "the corona's 0.35 of the height", "the mitred returns"]},
    "sill": {"photo_today": ["a deep sill group (140 mm: bead, cove, soffit) over the stallriser's frame; sill top 844 at the window's own plane, 0.172 of the front (0.61 m at 3.55 m; the scene's 600 is within 2 per cent)"], "earlier_notes": ["weathered top, drip, cill 'substantial' (BH, CW); Ellis's stout sill 3 in"], "judgement": ["75 thick, the throat 6 x 6, the weathering 15 degrees"]},
    "stallriser": {"photo_today": ["a framed panel under the sill, a bottom rail above the foot (P1: a cast grille panel, 609 high at the window plane)"], "earlier_notes": ["600 and 0.15 proud (scene); panelled, glazed tile, render; patterned tile and plain glazed tile on metal fronts (R05, R09); white tile and slab in fish shops"], "judgement": ["tile sizes and courses, the 2 x 2 pattern, the slab, the boarded sheet"]},
    "window_frame": {"photo_today": ["a mid transom bar and a heavy mullion (172 mm at the window's own plane, 0.15 of the light): partly followed", "stile 77 mm (42 px): not followed (jamb 50)", "the sill group's top is the glazing rebate's foot: the lights stand on the sill"], "earlier_notes": ["sill 600 to head 2850, transom 2400 to 2480, toplights, mullions 40-70 proud of the glass, glass 30 forward (scene, kit, CW)"], "judgement": ["every section's size and shape (T1, T2, M1, M2), bead sizes, bar positions, toplight counts", "the 25 mm seat"]},
    "shop_door": {"photo_today": ["glazed from 0.304 of the leaf (798 of 2624 mm on the door's plane; 620 on 2040), level with its window's sill to within 46 mm", "a 29 mm brass foot strip", "an octagonal knob on the lock rail (alternative)"], "earlier_notes": ["900 x 2040, frame 1006, kick plate, levers, hinges (kit); 'two-thirds glazed' (BH); the door's bottom panel the stallriser's height (Coventry); bottom rail 9 in (Ellis)"], "judgement": ["rail and stile widths, the lock rail 490 to 600, furniture heights (the letter plate at z 545 in the lock rail), the aluminium and bronze leaves"], "sheet": ["the hinge sides and the plate's place in the lock rail: the game's Rita frame"]},
    "side_door_slot": {"photo_today": [], "earlier_notes": ["the front-door family's F1 (its own photographs P2 and the books)"], "judgement": ["the mapping into the bay (d 100, z + 45, the trimmed head and threshold)"], "sheet": ["F1's hinge side: mirrored where the door end is the viewer's left (the game's Rita frame)"]},
    "lobby": {"photo_today": [], "earlier_notes": ["recessed lobbies with terrazzo or tiled floors (CW, HE1, HE2); a recessed doorway and tiled threshold in Marshall's West Dock Cafe (R05 reading)"], "judgement": ["the depths 600 and 300, the returns, the floors' patterns"]},
    "alterations": {"photo_today": ["roller-shutter hood depth (150 to 300) and rail width from CC0 scans (P2)"], "earlier_notes": ["metal fronts, patterned tile, letting boards, whitewash (R05, R09, DECISIONS 3 Oct)"], "judgement": ["every section size, every colour, the shutter's curtain plane (170), rails (d 150 to 190) and hood (210), the box sign and flat panel depths (the fascia target's)"]},
}

GAME_TODAY = {
    "source": "production/previews/rita-day-kit-2026-10-06.jpg, 1600 x 900: the game's Rita front today (the approved model)",
    "kind": "Sheet (measured on the frame by eye and colour, +-2 px)",
    "side_door": {"leaf_x_px": [215.7, 397.3], "knob_x_px": [225.7, 220.0], "knob_y_px": [487.7, 567.7], "knob_side": "viewer's left (the pier side)",
                  "hinge_side": "viewer's right (the shop-door side)"},
    "shop_door": {"glass_x_px": [457.7, 604.0], "lever_rose_x_px": [446.7, 475.0], "lever_y_px": 556.7, "lever_side": "viewer's left (the side-door side, left of the glass)",
                  "hinge_side": "viewer's right (the window side)", "letter_plate_x_px": [493.3, 561.7], "letter_plate_y_px": [582.3, 598.7],
                  "plate": "in the lock rail between the glass's foot (y 563) and the lower panel's top (y 612), centred on the leaf's width (leaf centre x about 530)"},
    "rule": "the shop door is hinged on the window side with its lever on the opposite edge; the side door on the shop-door side with its knob on the pier side; the letter plate centred on each leaf; mirrored where the doors are on the viewer's right",
    "note": "the game's glazed-from is 1.0 (the scene's value: glass foot at y 563 against the window's sill at y 655); the target's 600 follows P1 and the review",
}

REVIEW_FAULTS = [
    {"n": 1, "fault": "the shop door's glass started at 700 from a mis-snapped edge (row 95.7, strength 1.5)", "answer": "door_glass_bottom re-snapped at row 128.93 (strength 12.2) on a masked door preview (rows 128.9, 531.6, 547.0 re-measurable); glazed from 600 level with the sill; bottom_rail [0, 230], lower_panel [230, 490], lock_rail [490, 600]; R6 0.304 against 0.294; D2 reworded; checks DOR-02 (600) and DOR-06 (door glass foot minus window sill top = 0 +-5 per T1/M2 shop)", "followed": True},
    {"n": 2, "fault": "the letter plate sat in the glass (z 800)", "answer": "250 x 40 centred at z 545 in the lock rail, 35 clear above and below; DOR-05 [1000, 545]; the octagonal knob alternative on the lock rail at z 545; the drawing now draws the plate", "followed": True},
    {"n": 3, "fault": "the plinth's head moulding (a hollow and a band) was dropped as 'P1 shows none'", "answer": "plinth_stepped_side carries a cavetto (quarter ellipse 24 x 95) and a band 21 high; the review's points are kept verbatim as plinth_tall_stepped_side (+30 in d); the kit's base ogee restored on the panel and flute variants (made 15 proud after the second review); 'P1 shows none' struck from meets and section 5; PIL-14 covers both and PIL-16/17 state them. The head sits at Rita's 600 (see fault 3b)", "followed": True},
    {"n": "3b", "fault": "the review's note: keep the plinth at 800 and name it as a visible change to Jafar's model", "answer": "NOT followed, by the coordinator's instruction and the photograph's own limit: P1's plinth is 1.33 times its sill and breaks Rita's line (the plinth's top level with the stallriser), and Rita's window is Jafar's model. The plinth stays 600 on every front; 800 survives only as the unused variants.plinth_tall; R1 and R2 are 'not followed (Rita's line)'; the lower blocks of the stepped plinth are shortened (360 / 450 / 484 against P1's 504 / 631 / 684) and the head kept whole", "followed": False},
    {"n": 4, "fault": "pilasters 10 to 15 mm proud of the frames; the capital hardly flared", "answer": "shaft 140, plinth 180, capital die 144, hollow flare 144 to 172 over 90, abacus 175, top 350 x 175; every pilaster plan and side profile moved; the downpipe stands 12 behind the shafts; new check PIL-15 (the shaft 40 or more in front of every frame beside it, per shop in shops[].relief_beside_frames); D3 reworded", "followed": True},
    {"n": 5, "fault": "the 'scrolled' console was a plain corbel with a decal spiral", "answer": "side_silhouette redrawn as a two-volute scroll; after the second review (its narrower and deeper amendment, see fixes_after_second_review) a 240 x 205 x 550 scroll with a foot 240 x 172 on the capital, a lower volute (eye (158, 48) r 26, reaching 184), a waist narrowest 140 at z 140, a stem 150 at z 330, an upper volute (eye (160, 468) r 45, front 205, top (160, 513)) and a cap block 205 deep at z 528 to 550; grooves 8 inside the outline, 5 wide and 4 deep, ending in 16 mm eye bosses 3 proud; the leaf kept (z 150 to 420); CON-07/08/09 recomputed from the outline itself; the console is the first item of could_not_settle", "followed": True},
    {"n": 6, "fault": "no hinge side for any door, so a mirrored door passed every check", "answer": "shops[].shop_door_hinge_viewer, shop_door_lever_viewer, side_door_hinge_viewer, side_door_knob_viewer, letter_plate_viewer, taken from Rita's front in the game (game_today); check DOR-07 and the drawing follow. PARTLY DISAGREES with the review: in the game frame the side door's knobs are at x 225.7 and 220.0 on a leaf from 215.7 to 397.3, its LEFT edge (the pier side), so it is hinged on the viewer's right (the shop-door side), not the pier side; F1 is therefore mirrored where the door end is the viewer's left (D12)", "followed": "partly"},
    {"n": 7, "fault": "the roller shutter's curtain was at the glass plane, inside the frames", "answer": "curtain plane d 170 (20 clear of the sill's nose), guide rails 50 x 40 at d 150 to 190, z 0 to 2550, on steel spacer brackets through the frames into the pilaster core, hood 300 high x 210 deep, set into the toplight zone (the head, bars and glass cut away behind it, after the second review); the newsagent's glazing note: the hood hides the toplights above 2550, 70 shows; ALT-01, ALT-02 and ALT-07 follow; the drawing shows the hood and rails", "followed": True},
    {"n": 8, "fault": "the cornice's ends at the party-wall gaps were not defined", "answer": "each end closed by a mitred return of the full 19-point section back to the wall, 215 deep (cornice.ends; profiles return_left_uz / return_right_uz and the plans); the lead dressed over it with a 25 upstand; COR-06; a plan drawing of the end", "followed": True},
    {"n": 9, "fault": "the newsagent's board was dove grey, cream in the fascia target", "answer": "shops[newsagent].paints.fascia_board is cream (222, 209, 175); the piers, consoles and cornice stay dove grey; ALT-08", "followed": True},
    {"n": 10, "fault": "numbers labelled Photo that P1 does not show (stile 145, sill top 883, crown 446, capital 301, 'between the gilt keylines')", "answer": "stile_right re-snapped at -993.0 (stile 77 mm at the window plane, 41 px); the window rows use the window's own foot row (1.8666 mm a pixel): sill top 844, R3 0.172, R1 1.330, mullion 172; the crown withdrawn (R8 'not measurable', the true crown 170 to 300, the tall variant has no photographic basis); the capital marked an upper bound; the field renamed 'the board between the crown and the capital top'; the scale note adds the D.p/(D - p) rule", "followed": True},
    {"n": 11, "fault": "STA-03's arithmetic contradicted its own variant", "answer": "the measure text reads 'skirting 100 + two courses at 155.4 pitch + one half course at 79.2 + cap 35 = 525', expected 525 +-2", "followed": True},
    {"n": "notes", "fault": "the review's narrow points", "answer": "an overlay of the target's Rita elevation on the re-projected pier at the shaft's width with a differences table (photo.rita_vs_p1, previews P1-leadenhall-pier-elevation-ritas-on-photo); the laundry's refit and the vent pipe added to could_not_settle; the kick plate and foot strip: the strip is the plate's lowest 30; the drawings (D2) now show the whitewash, the laundry's box sign, the tea room's panel and the grocer's slabs; the A5 notice's statutory size noted, from memory", "followed": True},
]


FIXES_AFTER_SECOND_REVIEW = [
    {"n": 1, "fault": "the consoles stood behind the fascia board's bed mould and set back on the deeper capital (the re-review's one fault)", "fix": "side_silhouette redrawn within 240 x 205 x 550: foot 240 x 172 on the capital's flat; lower volute eye (158, 48) r 26 reaching d 184; waist narrowest d 140 at z 140; stem d 150 at z 330; upper volute eye (160, 468) r 45, front d 205 at z 468, top (160, 513), 1.25 turns; cap block 205 deep at z 528 to 550; grooves 8 inside the outline ending in 16 mm bosses; leaf on the front between z 150 and 420. CON-01 [240, 205, 550], CON-03 the foot 240 x 172 within the capital's top, CON-07 the new eyes, radii and waist, COR-02 oversail [95, 10], and new CON-09: the console's front at least 140 at every z from 2850 to 3400 (so also in front of the bed mould, 132, and the board, 120: no board end stands proud of it). The meets row 'console and capital' (and 'fascia board and console', 'cornice and fascia') rewritten.", "followed": True},
    {"n": "p1", "fault": "narrow point 1: the base ogee overhangs the timber plinth's flat (a gap of up to 11 mm under its front edge)", "fix": "base_ogee 15 proud, with the review's points (140, 600) (155, 600) (155, 608) (152.6, 612) (149, 617) (146, 624) (143.6, 633) (141.8, 645) (140, 660); PIL-17 [15, 60, 600]; the check against the kit's BASE (25 proud) is now a reported departure and the review's points are the Read.", "followed": True},
    {"n": "p2", "fault": "narrow point 2: the shutter's hood occupied the frames' space (the head, the toplight bars and the glass) and the overlap test left the hood out", "fix": "the hood is SET INTO the toplight zone: the window's and the shop door's head, the toplight bars and the toplight glass are cut away at z 2550 behind it over u 350 to 4706 (the drawing clips them; 70 of the toplights shows below); the hood is in the overlap test (the guide rails, which stand in front at d 150 to 190, are tested in the section, 50 clear of every frame); new ALT-09 and a recorded `cut_away`.", "followed": True},
]
