// GENERATED by tools/content-gate.py --emit-core. DO NOT EDIT BY HAND:
// the gate is the one list, and --emit-core --check fails when this differs.
using System.Text.RegularExpressions;

namespace Ledger.Core
{
    /// D18's speech rules, as the content gate states them, for the one text
    /// no person writes or reviews: a model's reply. ContentRule.SpeechBreaks
    /// reads this.
    public static class ContentWords
    {
        public sealed class Rule
        {
            public readonly string Kind, Id;
            public readonly Regex Pattern;
            public Rule(string kind, string id, bool cased, string pattern)
            {
                Kind = kind; Id = id;
                Pattern = new Regex(pattern, (cased ? RegexOptions.None : RegexOptions.IgnoreCase)
                                             | RegexOptions.CultureInvariant);
            }
        }

        public static readonly Rule[] Speech =
        {
            new Rule("alcohol", "beer", false, @"\bbeers?\b"),
            new Rule("alcohol", "lager", false, @"\blagers?\b"),
            new Rule("alcohol", "ale", false, @"\bales?\b"),
            new Rule("alcohol", "stout", false, @"\bstouts?\b"),
            new Rule("alcohol", "bitter_noun", false, @"(?:\b(?:pints?|halves?|half|glass(?:es)?|drinks?|drinking|pulling|pour\w*|serv\w*)\s+(?:of\s+)?bitter\b)|(?:\ba bitter\b(?!\s+[a-z]))|(?:\b(?:his|her|my|your|their|our|the usual)\s+bitter\b(?!\s+[a-z]))"),
            new Rule("alcohol", "mild_noun", false, @"(?:\b(?:pints?|halves?|half|glass(?:es)?|drinks?|drinking|pulling|pour\w*|serv\w*)\s+(?:of\s+)?mild\b)|(?:\bthe mild\b(?!\s+(?:weather|winter|spring|summer|autumn|day|night|case|form|version|one|steel|soap|cheese|sort|kind|manner)))"),
            new Rule("alcohol", "pint", false, @"\bpints?\b(?!\s+(?:bottles?|of\s+(?:milk|water|cream|paraffin|oil|blood|tea|squash)))(?<!milk pint)"),
            new Rule("alcohol", "whisky", false, @"\bwhisk(?:e)?y\b"),
            new Rule("alcohol", "vodka", false, @"\bvodkas?\b"),
            new Rule("alcohol", "gin_drink", false, @"\b(?:glass(?:es)?|bottles?|measures?|tots?|drop|shot|double)\s+of\s+gin\b|\bgin\s+and\s+(?:tonic|it|orange|lime)\b"),
            new Rule("alcohol", "brandy", true, @"\bbrandy\b"),
            new Rule("alcohol", "sherry", true, @"\bsherry\b"),
            new Rule("alcohol", "rum_drink", false, @"\b(?:glass(?:es)?|bottles?|measures?|tots?|drop|shot|double)\s+of\s+rum\b|\brum\s+and\s+(?:coke|black|pep)\b"),
            new Rule("alcohol", "wine", false, @"\bwines?\b"),
            new Rule("alcohol", "cider", false, @"\bciders?\b"),
            new Rule("alcohol", "champagne", false, @"\bchampagne\b"),
            new Rule("alcohol", "cocktail", false, @"\bcocktails?\b"),
            new Rule("alcohol", "liquor", false, @"\bliqueurs?\b|\bliquor\b"),
            new Rule("alcohol", "spirits_drink", false, @"\b(?:bottled?|bottles?\s+of|optics?|shelf\s+of|measures?\s+of|serv\w+|sell\w*|selling)\s+spirits\b|\bspirits\s+(?:optic|shelf|measure|licence|bottle)s?\b"),
            new Rule("alcohol", "booze", false, @"\bbooze\b|\bboozing\b"),
            new Rule("alcohol", "boozer", false, @"\bboozer\b"),
            new Rule("alcohol", "shandy", false, @"\bshandy\b"),
            new Rule("alcohol", "snakebite", false, @"\bsnakebite\b"),
            new Rule("alcohol", "grog", false, @"\bgrog\b"),
            new Rule("alcohol", "tipple", false, @"\btipple\b"),
            new Rule("alcohol", "nightcap", false, @"\bnightcaps?\b"),
            new Rule("alcohol", "tankard", false, @"\btankards?\b"),
            new Rule("alcohol", "firkin", false, @"\bfirkins?\b"),
            new Rule("alcohol", "cask", false, @"\bcasks?\b"),
            new Rule("alcohol", "keg", false, @"\bkegs?\b"),
            new Rule("alcohol", "brewery", false, @"\bbrewer(?:y|ies|s)?\b"),
            new Rule("alcohol", "offlicence", false, @"\boff-?licen[cs]es?\b|\boffies?\b"),
            new Rule("alcohol", "lastorders", false, @"\blast orders\b"),
            new Rule("alcohol", "lockin", false, @"\block-?ins?\b"),
            new Rule("alcohol", "happyhour", false, @"\bhappy hour\b"),
            new Rule("alcohol", "freehouse", false, @"\bfree\s?house\b|\btied\s?house\b"),
            new Rule("alcohol", "pubcrawl", false, @"\bpub crawls?\b"),
            new Rule("alcohol", "pump", false, @"\bpump ?clips?\b|\bbeer pumps?\b|\bbar pumps?\b|\bhand ?pulls?\b"),
            new Rule("alcohol", "beermat", false, @"\bbeer ?mats?\b"),
            new Rule("alcohol", "optic", false, @"\boptics?\b"),
            new Rule("alcohol", "drinkware", false, @"\b(?:wine|beer|pint|spirit)\s?glass(?:es)?\b"),
            new Rule("alcohol", "drunk", false, @"\bdrunks?\b|\bdrunken(?:ness)?\b|\bdrunkards?\b"),
            new Rule("alcohol", "drinking", false, @"\bdrinking\b"),
            new Rule("alcohol", "sober", false, @"\bsober(?:s|ed|ly)?\b"),
            new Rule("alcohol", "pissed", false, @"\bpissed\b(?!\s+(?:off|about|down|on|up|myself|himself|herself|themselves|it))"),
            new Rule("alcohol", "tipsy", false, @"\btipsy\b|\bsozzled\b|\bsloshed\b|\blegless\b|\bparalytic\b|\bsquiffy\b|\btiddly\b|\bhalf-?cut\b|\bthree sheets\b"),
            new Rule("alcohol", "hangover", false, @"\bhang-?overs?\b|\bhungover\b"),
            new Rule("alcohol", "teetotal", false, @"\bteetotal\w*\b"),
            new Rule("alcohol", "onthesauce", false, @"\bon the sauce\b|\bhair of the dog\b|\bone for the road\b"),
            new Rule("alcohol", "aroundofdrinks", false, @"\b(?:a|your|my|his|her|their|our|whose|another|next)\s+round\b(?!\s+(?:of\s+applause|trip|the|here|robin|number|figure))"),
            new Rule("gambling", "gambling", false, @"\bgambl\w*\b"),
            new Rule("gambling", "betting", false, @"\bbetting\b|\bbettors?\b|\bbet\s+on\s+(?:the\s+)?(?:horses|dogs|race|races|match|game|fight|nose)\b|\bhad a bet\b|\bplace[ds]? a bet\b|\btakes? bets\b|\blay(?:s|ing)? (?:a )?bet\b"),
            new Rule("gambling", "bettingslip", false, @"\bbet(?:ting)? ?slips?\b"),
            new Rule("gambling", "bookie", false, @"\bbookies?\b|\bbookmakers?(?:'s)?\b|\bturf accountants?\b"),
            new Rule("gambling", "oddson", false, @"\bodds-?on\b|\bodds\s+of\s+\d|\b(?:short|long|better)\s+odds\b"),
            new Rule("gambling", "wager", false, @"\bwager\w*\b"),
            new Rule("gambling", "fruitmachine", false, @"\bfruit machines?\b|\bone-?armed bandits?\b|\bslot machines?\b|\bpuggys?\b"),
            new Rule("gambling", "jackpot", false, @"\bjackpots?\b"),
            new Rule("gambling", "poker_game", false, @"(?<!fire )(?<!coal )(?<!brass )(?<!iron )(?<!hearth )\bpoker\b(?!\s*face)"),
            new Rule("gambling", "blackjack", false, @"\bblackjack\b"),
            new Rule("gambling", "roulette", false, @"\broulette\b|\bbaccarat\b|\bcraps\b"),
            new Rule("gambling", "bingo", false, @"\bbingo\b"),
            new Rule("gambling", "lottery", false, @"\blotter(?:y|ies)\b"),
            new Rule("gambling", "raffle", false, @"\braffles?\b|\btombolas?\b|\bsweepstakes?\b"),
            new Rule("gambling", "pools", false, @"\bthe pools\b|\bfootball pools\b|\bpools coupons?\b"),
            new Rule("gambling", "accumulator", false, @"\baccumulators?\b"),
            new Rule("gambling", "stakeon", false, @"\bstake[ds]?\s+on\b|\bstakes\s+on\b"),
            new Rule("gambling", "dogtrack", false, @"\bdog tracks?\b|\bgreyhound\s+(?:racing|track|stadium)\b|\brace\s?courses?\b|\bracetracks?\b|\brace meetings?\b"),
            new Rule("gambling", "threecard", false, @"\bthree-?card\b|\bfind the lady\b|\bcrown and anchor\b"),
            new Rule("gambling", "moneyongame", false, @"\b(?:fiver|tenner|quid|pound|score)\s+on\s+(?:the\s+)?(?:horses|dogs|match|game|fight|nose|favourite)\b|\bcards for money\b|\bpenny a point\b"),
            new Rule("gambling", "dice", false, @"\bdice\b"),
            new Rule("gambling", "casino", false, @"\bcasinos?\b|\bbetting shops?\b|\bamusement arcades?\b"),
            new Rule("children", "child", false, @"\bchild(?:ren|ren's|'s|s)?\b"),
            new Rule("children", "kid", false, @"\bkids?\b"),
            new Rule("children", "baby", false, @"\bbab(?:y|ies)\b|\btoddlers?\b|\binfants?\b|\bnewborns?\b"),
            new Rule("children", "pram", false, @"\bprams?\b|\bpushchairs?\b|\bperambulators?\b"),
            new Rule("children", "schoolchild", false, @"\bschool\s?(?:boys?|girls?|child(?:ren)?|kids?)\b|\bpupils?\b|\bschool\s?yards?\b|\bplaygrounds?\b|\bnurser(?:y|ies)\b|\bcreche\b|\bschool\s?runs?\b|\bschool\s?uniforms?\b|\bschool\s?bells?\b|\b(?:infant|primary|junior|secondary|nursery)\s+schools?\b|\bschool\s?bus(?:es)?\b"),
            new Rule("children", "satchel", false, @"\bsatchels?\b"),
            new Rule("children", "littlechild", false, @"\b(?:little|young|small|wee)\s+(?:boys?|girls?|lads?|lasses)\b"),
            new Rule("children", "teenager", false, @"\bteenagers?\b|\bteenaged?\b|\byoungsters?\b|\badolescents?\b|\bjuveniles?\b|\bschoolleavers?\b|\bschool leavers?\b"),
            new Rule("children", "underage", false, @"\baged?\s+(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|[1-9]|1[0-7])\b|\b(?:[1-9]|1[0-7])[-\s]years?[-\s]old\b"),
            new Rule("drugs", "hardsubstance", false, @"\bheroin\b|\bcocaine\b|\bcannabis\b|\bmarijuana\b|\bamphetamines?\b|\bbarbiturates?\b|\bmethadone\b|\bmandrax\b|\blsd\b|\bspliffs?\b|\breefers?\b|\bsmack\b(?!\s+(?:in|on|of|him|her|them|it))"),
            new Rule("drugs", "druguse", false, @"\bshoot(?:ing)? up\b|\binject(?:ed|ing|s)?\b|\bsyringes?\b|\bsnort(?:ed|ing|s)?\b|\btrack marks?\b|\bskin(?:ning)? up\b|\brolling a joint\b|\bstoned\b|\bdoped up\b|\boverdos(?:e|ed|ing)\b|\bneedle in (?:his|her|their|the) arm\b|\bdirty needles?\b|\bwrap of\b|\bbaggies?\b|\bline of (?:coke|charlie|whizz)\b"),
            new Rule("sex", "prostitution", false, @"\bprostitut\w*\b|\bbrothels?\b|\bhookers?\b|\bwhores?\b|\bkerb.?crawl\w*\b|\bstreet.?walkers?\b|\bmassage parlours?\b|\bon the game\b|\bred.?light\b|\bworking girls?\b|\bpimps?\b"),
            new Rule("sex", "sexual", false, @"\bsexual(?:ly)?\b|\bsexy\b|\b(?:had|having|have)\s+sex\b|\bsex\s+(?:with|scene|act|worker)\b|\bnaked\b|\bnude\b|\bnudity\b|\btopless\b|\bporn\w*\b|\bfellati\w*\b|\bmasturbat\w*\b|\borgasm\w*\b|\berotic\w*\b"),
            new Rule("cruelty", "torture", false, @"\btortur\w*\b|\bkneecap(?:ped|ping)?\b|\bblowtorch\w*\b|\bpliers on\b|\bfingernails? (?:out|off|pulled)\b|\bmutilat\w*\b|\bdismember\w*\b|\bdisembowel\w*\b"),
            new Rule("slur", "slur", false, @"\bnigger\b|\bnigga\b|\bnignog\b|\bnig\-nog\b|\bjungle\ bunny\b|\bgolliwog\b|\bdarkie\b|\bdarky\b|\bsambo\b|\bcoon\b|\bwog\b|\bhalf\-caste\b|\bhalf\ caste\b|\bkike\b|\byid\b|\bhymie\b|\bsheeny\b|\bpaki\b|\braghead\b|\btowelhead\b|\bchinaman\b|\bjap\b|\bdago\b|\bwop\b|\beyetie\b|\bkraut\b|\bpolack\b|\bbog\-trotter\b|\btaig\b|\bgyppo\b|\bgippo\b|\bpikey\b|\bpoofter\b|\bnonce\b|\bspastic\b|\bspastics\b|\bmongoloid\b|\bretard\b|\bretarded\b|\bwetback\b"),
        };
    }
}
