// THE GOLDEN TABLE'S READER AND THE PORT'S ANSWER, IN A FILE THAT COMPILES
// WITHOUT UNREAL.
//
// WHAT THE GOLDEN TABLE IS. ledger/PerceptionGolden/Program.cs runs the REAL
// Ledger.Core as shipped and writes ue-probe/perception-golden.txt: one row
// per case, `fn|args...|expected`. The C++ transliteration under LedgerCore
// reads the same file and must agree. A table generated by the original and
// consumed by the port has ONE source of truth and no second implementation
// of the expectations, which is why it exists instead of a ported test
// suite: porting 130 NUnit methods would prove the port agrees with a SECOND
// transliteration rather than with the original.
//
// WHY THE DISPATCH LIVES HERE AND NOT IN LedgerProbe.cpp. The standing rule
// from 25 August: measurement arithmetic and formatting live where the tests
// run. LedgerProbe.cpp compiles only on Jafar's PC, so a dispatcher written
// there ships UNRUN and the first thing that finds out whether it works is a
// 25-minute round trip. Everything that can be wrong about READING a row and
// ANSWERING it is therefore in this header, and
// ue-probe/tests/core-port-test.cpp compiles it with g++ and runs it against
// the REAL committed table before anything is dispatched. The module
// supplies the file's bytes and nothing else.
//
// NO VALUE IN THE TABLE CONTAINS A SPACE, A NEWLINE OR A PIPE, and that is
// this project's own rule rather than a convenience: every reader here
// splits on a delimiter and truncates silently when one appears. Strings
// travel escaped, space as ~, newline as ^, pipe as !, and both engines use
// the same three substitutions. A fixture carrying one of the three
// substitute characters would round-trip wrongly, so neither side is allowed
// to build one, and Escape says so where it happens.
//
// THE SCENARIOS ARE THE FIXTURE WRITTEN TWICE, and that is a real cost named
// rather than hidden. A stateful thing (a memory that prunes, a mill that
// ticks) cannot be described by one row of arguments, so each scenario is
// built by both engines and its READINGS are compared. If the two builders
// ever drift apart the readings disagree and the test goes red; the failure
// mode this cannot have is a silent pass, because a silent pass would need
// both builders to be wrong in the same way at the same time.
#pragma once

#include "GameTime.h"
#include "Gossip.h"
#include "SaveCodec.h"
#include "MemoryStore.h"
#include "Observation.h"
#include "Perception.h"
#include "Suspicion.h"

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

namespace LedgerCore
{
namespace Golden
{
	// ---- the table's small vocabulary -------------------------------

	inline std::string Escape(const std::string& S)
	{
		std::string Out;
		Out.reserve(S.size());
		for (std::string::size_type I = 0; I < S.size(); ++I)
		{
			const char C = S[I];
			if      (C == ' ')  Out += '~';
			else if (C == '\n') Out += '^';
			else if (C == '\r') { /* dropped: a line ending is a platform fact */ }
			else if (C == '|')  Out += '!';
			else                Out += C;
		}
		return Out;
	}

	inline std::string Unescape(const std::string& S)
	{
		std::string Out;
		Out.reserve(S.size());
		for (std::string::size_type I = 0; I < S.size(); ++I)
		{
			const char C = S[I];
			if      (C == '~') Out += ' ';
			else if (C == '^') Out += '\n';
			else if (C == '!') Out += '|';
			else               Out += C;
		}
		return Out;
	}

	inline std::string FromBool(bool B) { return B ? "1" : "0"; }

	inline std::string FromInt(long long V)
	{
		char Buf[32];
		std::snprintf(Buf, sizeof(Buf), "%lld", V);
		return std::string(Buf);
	}

	// The shortest decimal that reads back as this double, which is what
	// C#'s "R" writes into the table.
	inline std::string FromDouble(double V) { return ShortestRoundTrip(V); }

	inline double D(const std::string& S) { return std::strtod(S.c_str(), 0); }
	inline bool   B(const std::string& S) { return S == "1"; }
	inline int    I(const std::string& S) { return (int)std::strtol(S.c_str(), 0, 10); }

	inline bool IsNumber(const std::string& S)
	{
		if (S.empty()) return false;
		char* End = 0;
		std::strtod(S.c_str(), &End);
		return End != 0 && *End == '\0';
	}

	// TWO NUMBERS COMPARE NUMERICALLY, EVERYTHING ELSE COMPARES EXACTLY.
	// A string answer with one character wrong is a failure however close it
	// looks, and a double is never asked to be bit-identical across two
	// runtimes' libm.
	inline bool Agrees(const std::string& Got, const std::string& Want, double Tol)
	{
		if (IsNumber(Got) && IsNumber(Want))
		{
			const double A = D(Got), Bv = D(Want);
			const double Diff = A > Bv ? A - Bv : Bv - A;
			return Diff <= Tol;
		}
		return Got == Want;
	}

	inline std::vector<std::string> SplitPipe(const std::string& Line)
	{
		std::vector<std::string> Out;
		std::string Cur;
		for (std::string::size_type P = 0; P < Line.size(); ++P)
		{
			if (Line[P] == '|') { Out.push_back(Cur); Cur.clear(); }
			else                { Cur += Line[P]; }
		}
		Out.push_back(Cur);
		return Out;
	}

	// ---- the scenarios ----------------------------------------------
	//
	// Each one builds a world, then reads it. The keys are the contract with
	// ledger/PerceptionGolden/Program.cs, which builds the same world in C#
	// and writes the same keys with the C#'s answers.

	typedef std::vector<std::pair<std::string, std::string> > Readings;

	inline void Put(Readings& R, const std::string& Key, const std::string& Value)
	{
		R.push_back(std::make_pair(Key, Value));
	}

	inline std::string LineOf(const MemoryStore& S, int Index)
	{
		if (Index < 0 || Index >= (int)S.Events.size()) return "NO-SUCH-LINE";
		return Escape(S.Events[(std::vector<MemoryEvent>::size_type)Index].ToLine());
	}

	inline bool AlwaysTogether(const std::string&, const std::string&) { return true; }
	inline bool NeverTogether(const std::string&, const std::string&)  { return false; }

	inline void ScenarioMemBasic(Readings& R)
	{
		MemoryStore S("w1");
		S.Append(MemoryEvent(GameTime(1, 12, 0), "observation", 0.6,
		                     "a window on the Parade went in"));
		S.Append(MemoryEvent(GameTime(1, 12, 5), "heard", 0.36096,
		                     "I heard from the shopkeeper that a window went in"));
		// A newline inside the text and space either end of it: the
		// constructor replaces the one and trims the other, and this is the
		// only case that proves it did.
		S.Append(MemoryEvent(GameTime(2, 9, 0), "reflection", 0.125,
		                     "  two lines\nbecome one  "));
		Put(R, "count", FromInt((long long)S.Events.size()));
		Put(R, "day1", FromInt((long long)S.EventsOnDay(1).size()));
		Put(R, "day2", FromInt((long long)S.EventsOnDay(2).size()));
		Put(R, "day3", FromInt((long long)S.EventsOnDay(3).size()));
		Put(R, "line0", LineOf(S, 0));
		Put(R, "line1", LineOf(S, 1));
		Put(R, "line2", LineOf(S, 2));
		Put(R, "markdown", Escape(S.ToMarkdown()));
	}

	inline void ScenarioMemPermanent(Readings& R)
	{
		// WAS ScenarioMemPrune. Jafar ruled queue 115 on 2026-09-14: canon.md
		// line 99 stands, nothing is ever wiped, and MaxEvents/PruneTo left
		// both engines in the same change.
		//
		// THE APPEND COUNTS ARE UNCHANGED AT 601 AND 701 ON PURPOSE, because
		// those are the appends that used to trigger the cap: a scenario that
		// stopped crossing it would prove nothing about the engine that
		// removed it. countAfter601 was 500 and is 601; countAfter701 was
		// 600 and is 701.
		//
		// The importances still ascend one per event. They no longer decide
		// which event survives, since all of them do, but e0 is the weakest
		// and the oldest, so firstTextAfter701 is canon stated cross-engine.
		// firstTextAfter601 was e101 and is e0, which names the 101 weakest
		// events of the older half the cap used to take.
		MemoryStore S("w1");
		for (int Idx = 0; Idx <= 600; ++Idx)
		{
			S.Append(MemoryEvent(GameTime(1, Idx / 60, Idx % 60), "observation",
			                     Idx / 1000.0, "e" + FromInt(Idx)));
		}
		Put(R, "countAfter601", FromInt((long long)S.Events.size()));
		Put(R, "firstImportanceAfter601", FromDouble(S.Events[0].Importance));
		Put(R, "firstTextAfter601", Escape(S.Events[0].Text));
		Put(R, "lastImportanceAfter601", FromDouble(S.Events[S.Events.size() - 1].Importance));
		for (int Idx = 601; Idx <= 700; ++Idx)
		{
			S.Append(MemoryEvent(GameTime(1, Idx / 60, Idx % 60), "observation",
			                     Idx / 1000.0, "e" + FromInt(Idx)));
		}
		Put(R, "countAfter701", FromInt((long long)S.Events.size()));
		Put(R, "firstImportanceAfter701", FromDouble(S.Events[0].Importance));
		Put(R, "lastTextAfter701", Escape(S.Events[S.Events.size() - 1].Text));
		Put(R, "firstTextAfter701", Escape(S.Events[0].Text));
	}

	// The crime run's own scenario, built from the ruling's numbers: two
	// strangers on a tie of 0.60, one 0.94 sighting, then a round where they
	// are not together and a round where they are.
	inline void ScenarioGossipCrime(Readings& R)
	{
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));

		const Fact Content("player", "broke_window_d1", "east_parade_glass0");
		const std::string Summary = "a window on the Parade went in, and I would know the face again";
		Mill.Witness("w1", Content, Summary, false, GameTime(1, 12, 0), 0.94);

		Put(R, "tie", FromDouble(Mill.Tie("w1", "n2")));
		Put(R, "offered", FromInt(Mill.WitnessesOffered()));
		Put(R, "dropped", FromInt(Mill.WitnessesDropped()));
		GossiperPtr W1 = Mill.Get("w1");
		GossiperPtr N2 = Mill.Get("n2");
		Put(R, "w1Rumors", FromInt((long long)W1->Rumors.size()));
		Put(R, "w1Conf", FromDouble(W1->Rumors[0]->Confidence));
		Put(R, "w1Hops", FromInt(W1->Rumors[0]->Hops));
		Put(R, "w1Topic", Escape(W1->Rumors[0]->TopicKey()));
		Put(R, "w1Knowledge", FromInt((long long)W1->Knowledge->Facts.size()));
		Put(R, "w1MemCount", FromInt((long long)W1->Memory->Events.size()));
		Put(R, "w1MemLine0", LineOf(*W1->Memory, 0));
		Put(R, "saysPlayer", FromInt(Mill.SummariesSaying("player")));

		const std::vector<GossipEvent> R1 = Mill.Tick(GameTime(1, 12, 1), NeverTogether);
		Put(R, "r1Events", FromInt((long long)R1.size()));
		Put(R, "r1N2Rumors", FromInt((long long)N2->Rumors.size()));

		const std::vector<GossipEvent> R2 = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "r2Events", FromInt((long long)R2.size()));
		Put(R, "r2From", Escape(R2.empty() ? std::string("none") : R2[0].FromId));
		Put(R, "r2To", Escape(R2.empty() ? std::string("none") : R2[0].ToId));
		Put(R, "r2Conf", R2.empty() ? std::string("none") : FromDouble(R2[0].RumorRef->Confidence));
		Put(R, "r2Hops", R2.empty() ? std::string("none") : FromInt(R2[0].RumorRef->Hops));
		Put(R, "r2Contradiction", R2.empty() ? std::string("none") : FromBool(R2[0].Contradiction));
		Put(R, "r2Exposure", R2.empty() ? std::string("none") : FromBool(R2[0].Exposure));
		Put(R, "r2N2Rumors", FromInt((long long)N2->Rumors.size()));
		Put(R, "r2N2MemCount", FromInt((long long)N2->Memory->Events.size()));
		Put(R, "r2N2MemLine0", LineOf(*N2->Memory, 0));
		Put(R, "r2N2Knowledge", FromInt((long long)N2->Knowledge->Facts.size()));

		// The re-tell guard, from both ends: w1 has nothing stronger to add
		// and n2's copy is not worth passing back.
		const std::vector<GossipEvent> R3 = Mill.Tick(GameTime(1, 12, 3), AlwaysTogether);
		Put(R, "r3Events", FromInt((long long)R3.size()));
		Put(R, "r3N2Rumors", FromInt((long long)N2->Rumors.size()));
		Put(R, "r3W1Rumors", FromInt((long long)W1->Rumors.size()));
		Put(R, "r3N2MemCount", FromInt((long long)N2->Memory->Events.size()));

		// Gossiper::Holds and Gossiper::Best, which the mill's own ported
		// lines never call and which are inside the range the ruling named.
		// Holds asks about THIS version of the story, so the second reading
		// names the other window and must be 0.
		Put(R, "n2Holds", FromBool(N2->Holds("player.broke_window_d1", "east_parade_glass0")));
		Put(R, "n2HoldsOther", FromBool(N2->Holds("player.broke_window_d1", "east_parade_glass1")));
		Put(R, "w1BestConf", FromDouble(W1->Best("player.broke_window_d1")->Confidence));
		Put(R, "n2BestConf", FromDouble(N2->Best("player.broke_window_d1")->Confidence));
	}

	inline void ScenarioGossipDropped(Readings& R)
	{
		GossipMill Mill(std::make_shared<SocialGraph>());
		Mill.Witness("ghost", Fact("player", "broke_window_d1", "east_parade_glass0"),
		             "a window went in", false, GameTime(1, 12, 0), 1.0);
		Put(R, "offered", FromInt(Mill.WitnessesOffered()));
		Put(R, "dropped", FromInt(Mill.WitnessesDropped()));
		Put(R, "agents", FromInt((long long)Mill.Agents().size()));
	}

	inline void ScenarioGossipContradiction(Readings& R)
	{
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		// What the player told n2 to his face.
		Mill.Get("n2")->Knowledge->Learn(Fact("player", "location_d2_evening", "home"));
		Mill.Witness("w1", Fact("player", "location_d2_evening", "warehouse"),
		             "he was down at the warehouse", false, GameTime(1, 12, 0), 1.0);
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "contradiction", Ev.empty() ? std::string("none") : FromBool(Ev[0].Contradiction));
		Put(R, "exposure", Ev.empty() ? std::string("none") : FromBool(Ev[0].Exposure));
		Put(R, "passed", Ev.empty() ? std::string("none") : FromDouble(Ev[0].RumorRef->Confidence));
		GossiperPtr N2 = Mill.Get("n2");
		Put(R, "n2MemCount", FromInt((long long)N2->Memory->Events.size()));
		Put(R, "n2MemLine0", LineOf(*N2->Memory, 0));
		Put(R, "n2MemLine1", LineOf(*N2->Memory, 1));
	}

	inline void ScenarioGossipExposure(Readings& R)
	{
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the fence",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "night"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "night_business_d1", "the docks"),
		             "he was down the docks after midnight", true, GameTime(1, 12, 0), 1.0);
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "contradiction", Ev.empty() ? std::string("none") : FromBool(Ev[0].Contradiction));
		Put(R, "exposure", Ev.empty() ? std::string("none") : FromBool(Ev[0].Exposure));
	}

	inline void ScenarioGossipSuppressed(Readings& R)
	{
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "broke_window_d1", "east_parade_glass0"),
		             "a window on the Parade went in", false, GameTime(1, 12, 0), 0.94);
		Mill.Get("w1")->Suppressed.push_back("player.broke_window_d1");
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "n2Rumors", FromInt((long long)Mill.Get("n2")->Rumors.size()));
	}

	inline void ScenarioGossipLeashed(Readings& R)
	{
		// A leash holds everything ABOUT THE PLAYER and nothing else, so the
		// same speaker in the same round passes one rumour and not the other.
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "broke_window_d1", "east_parade_glass0"),
		             "a window on the Parade went in", false, GameTime(1, 12, 0), 0.94);
		Mill.Witness("w1", Fact("novak", "owes_money_d1", "forty pounds"),
		             "Novak is into somebody for forty", false, GameTime(1, 12, 0), 0.94);
		Mill.Get("w1")->Leashed = true;
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "passedSubject", Ev.empty() ? std::string("none") : Escape(Ev[0].RumorRef->Content.Subject));
	}

	inline void ScenarioGossipIndelible(Readings& R)
	{
		// A body arrives at the far end of the street exactly as true as it
		// left, so a tie of 0.1 that would kill any story passes this one.
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.1);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "killed_d1", "the docker"),
		             "he put the docker down and walked off", false,
		             GameTime(1, 12, 0), 1.0, true);
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "passed", Ev.empty() ? std::string("none") : FromDouble(Ev[0].RumorRef->Confidence));
		Put(R, "hops", Ev.empty() ? std::string("none") : FromInt(Ev[0].RumorRef->Hops));
		Put(R, "n2Knowledge", FromInt((long long)Mill.Get("n2")->Knowledge->Facts.size()));
	}

	inline void ScenarioGossipIndelibleFloor(Readings& R)
	{
		// THE SUBTLE ONE. An indelible rumour skips the first floor test and
		// then meets the second: passed is its own confidence, and 0.1 is
		// still under MinConfidenceToShare, so a corpse nobody is sure about
		// does not travel either.
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.9);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "killed_d1", "the docker"),
		             "somebody put the docker down", false, GameTime(1, 12, 0), 0.1, true);
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "w1Conf", FromDouble(Mill.Get("w1")->Rumors[0]->Confidence));
		Put(R, "w1Indelible", FromBool(Mill.Get("w1")->Rumors[0]->Indelible));
	}

	inline void ScenarioWitnessUpgrade(Readings& R)
	{
		// All four branches of Witness, in order, on one rumour: new, no
		// change, stronger, and the indelible upgrade in place. The memory
		// line is written on every one of the four.
		GossipMill Mill(std::make_shared<SocialGraph>());
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		const Fact F("player", "broke_window_d1", "east_parade_glass0");
		Mill.Witness("w1", F, "s1", false, GameTime(1, 12, 0), 0.5);
		Mill.Witness("w1", F, "s2", false, GameTime(1, 12, 1), 0.3);
		Mill.Witness("w1", F, "s3", false, GameTime(1, 12, 2), 0.9);
		Mill.Witness("w1", F, "s4", false, GameTime(1, 12, 3), 0.4, true);
		GossiperPtr W1 = Mill.Get("w1");
		Put(R, "rumors", FromInt((long long)W1->Rumors.size()));
		Put(R, "conf", FromDouble(W1->Rumors[0]->Confidence));
		Put(R, "hops", FromInt(W1->Rumors[0]->Hops));
		Put(R, "indelible", FromBool(W1->Rumors[0]->Indelible));
		Put(R, "summary", Escape(W1->Rumors[0]->Summary));
		Put(R, "knowledge", FromInt((long long)W1->Knowledge->Facts.size()));
		Put(R, "memCount", FromInt((long long)W1->Memory->Events.size()));
		// THE DOUBTFUL LINE, which is the string the crime run commits and
		// the one whose em-dash was corrected to a comma in both engines.
		Put(R, "memLine3", LineOf(*W1->Memory, 3));
		Mill.Witness("w1", Fact("player", "seen_d1", "the parade"), "s5",
		             false, GameTime(1, 12, 4), 1.0);
		Put(R, "memLine4", LineOf(*W1->Memory, 4));
		Put(R, "knowledgeAfterCertain", FromInt((long long)W1->Knowledge->Facts.size()));

		// BEST'S ONE SUBTLETY, GIVEN ITS OWN CASE. Two versions of one topic
		// at EQUAL confidence: C#'s OrderByDescending is a stable sort, so
		// the first added wins, and the port's strict > claims to reproduce
		// that without sorting. A port using >= would answer glass1 here.
		Mill.Witness("w1", Fact("player", "tie_d1", "glass0"), "t0", false,
		             GameTime(1, 12, 5), 0.5);
		Mill.Witness("w1", Fact("player", "tie_d1", "glass1"), "t1", false,
		             GameTime(1, 12, 6), 0.5);
		Put(R, "bestValueTie", Escape(W1->Best("player.tie_d1")->Content.Value));
		Put(R, "bestConfTie", FromDouble(W1->Best("player.tie_d1")->Confidence));
	}

	// THE NAMED FIXTURE, CoreTests/Program.cs 16019 to 16103, which the crime
	// ruling names as this port's own proof (section 8 item 3) and which the
	// director's review found no Resolve row reached. Its first claim is that
	// four positions produce FOUR DISTINCT slot sets, and the case it exists
	// for is "act, no actor": the victim falls in the market light at 9 m
	// while the shooter stands in a doorway at 24 m under 0.08 light. That is
	// the reason Sight was split off Vantage at all (Observation.cs 114 to
	// 126), and no other case in the table reaches it.
	//
	// THREE OF THE FIXTURE'S CONSTANTS ARE NOT IN THIS PORT'S SCOPE. The C#
	// deed reads Perception.LoudSuppressed22 (62), the market floor is
	// AmbientMarketNoon (58) and the loud weapon is LoudSnub38 (100); the
	// crime ruling's list ports none of the three, so the values travel as
	// literals here while the generator on the other side reads the real C#
	// constants. If one of them ever moves, these rows go red, which is the
	// right outcome for a number two engines are supposed to share.
	inline Vantage FourAt(const std::string& Id, double M, double Light, double Fam,
	                      bool bOcc = false, bool bMark = false, bool bFace = true,
	                      double Ambient = Perception::AmbientDaytimeStreet,
	                      double Watched = 3.0, bool bLater = false)
	{
		Vantage V = Vantage::Both(Id, M, Light, Fam, Ambient);
		V.ToActor.Occluded = bOcc; V.ToVictim.Occluded = bOcc;
		V.ActorHasMark = bMark; V.FaceToward = bFace;
		V.SecondsWatching = Watched; V.ArrivedLater = bLater;
		return V;
	}

	inline void PutObservation(Readings& R, const std::string& Prefix, const Observation& O)
	{
		Put(R, Prefix + "Slots", FromInt((long long)(int)O.Slots));
		Put(R, Prefix + "Rung", FromInt(O.Rung));
		Put(R, Prefix + "Certainty", FromDouble(O.Certainty));
		Put(R, Prefix + "Label", Escape(O.Label()));
		Put(R, Prefix + "Accused", Escape(O.AccusedId.empty() ? std::string("none") : O.AccusedId));
		Put(R, Prefix + "NamesSomebody", FromBool(O.NamesSomebody()));
	}

	inline void ScenarioObservationFour(Readings& R)
	{
		Deed Dd;
		Dd.EventId = "e1"; Dd.ActorId = "player"; Dd.VictimId = "tony";
		Dd.Loudness = 62.0;            // Perception.LoudSuppressed22, not ported
		Dd.VictimCriesOut = false; Dd.WeaponDrawn = true; Dd.ActorFled = true;
		Dd.LeavesBody = true; Dd.HadPrecursor = true;

		const Observation Close  = Observe::Resolve(Dd, FourAt("close", 4, 1.0, 0.9));
		const Observation Wall   = Observe::Resolve(Dd, FourAt("wall", 6, 1.0, 0.9, true));
		const Observation Later  = Observe::Resolve(Dd, FourAt("later", 1, 1.0, 0.9,
		                                                       false, false, true,
		                                                       Perception::AmbientDaytimeStreet,
		                                                       3.0, true));

		// THE SUPPRESSED-PISTOL CASE. One sightline for "the event" made this
		// unreachable, and a test asserting four different slot sets got
		// three.
		Vantage Across;
		Across.WitnessId = "across";
		Across.ToVictim = Sight::At(9, 1.0);      // he falls, right there, lit
		Across.ToActor  = Sight::At(24, 0.08);    // the shooter, in a doorway
		Across.Familiarity = 0.9;                 // even a friend cannot help here
		Across.AmbientFloor = 58.0;               // Perception.AmbientMarketNoon, not ported
		Across.FaceToward = true; Across.SecondsWatching = 3.0;
		const Observation Far = Observe::Resolve(Dd, Across);

		// The same witness, same relationship, with the shooter under a lamp
		// instead of in a doorway. Light is the whole difference.
		Vantage Lit = Across; Lit.ToActor = Sight::At(24, 1.0);
		const Observation Seen = Observe::Resolve(Dd, Lit);

		// A LOUD weapon through the same wall is a different story, and
		// hearing gives the act without the actor.
		Deed Loud = Dd; Loud.Loudness = 100.0;    // Perception.LoudSnub38, not ported
		const Observation WallLoud = Observe::Resolve(Loud, FourAt("wall", 6, 1.0, 0.9, true));

		// Sight::Blind(), the eye that does not exist (Witnesses.cs 86), which
		// is the shape the crime probe feeds for an out-of-world target.
		Vantage BlindV = FourAt("blindVictim", 4, 1.0, 0.9);
		BlindV.ToVictim = Sight::Blind();
		const Observation BlindObs = Observe::Resolve(Dd, BlindV);

		PutObservation(R, "close", Close);
		PutObservation(R, "wall", Wall);
		PutObservation(R, "later", Later);
		PutObservation(R, "across", Far);
		PutObservation(R, "litShooter", Seen);
		PutObservation(R, "wallLoud", WallLoud);
		PutObservation(R, "blindVictim", BlindObs);

		// CLAIM 1, and the whole reason the fixture exists: four witnesses,
		// four different slot sets. Counted over close, across, wall, later,
		// in that order, exactly as the C# counts it.
		int Sets[4];
		Sets[0] = (int)Close.Slots; Sets[1] = (int)Far.Slots;
		Sets[2] = (int)Wall.Slots;  Sets[3] = (int)Later.Slots;
		int Distinct = 0;
		for (int A = 0; A < 4; ++A)
		{
			bool bSeen = false;
			for (int Bx = 0; Bx < A; ++Bx) { if (Sets[Bx] == Sets[A]) bSeen = true; }
			if (!bSeen) ++Distinct;
		}
		Put(R, "distinctSets", FromInt(Distinct));

		const Sight Blind = Sight::Blind();
		Put(R, "blindMetres", FromDouble(Blind.Metres));
		Put(R, "blindLight", FromDouble(Blind.LightLevel));
		Put(R, "blindOccluded", FromBool(Blind.Occluded));
	}

	inline void ScenarioKnowledge(Readings& R)
	{
		KnowledgeBase K;
		const Fact Home("player", "location_d2_evening", "home");
		const Fact Ware("player", "location_d2_evening", "warehouse");
		Put(R, "empty", FromInt((long long)K.CheckClaim(Home)));
		K.Learn(Home);
		Put(R, "consistent", FromInt((long long)K.CheckClaim(Home)));
		Put(R, "contradiction", FromInt((long long)K.CheckClaim(Ware)));
		K.Learn(Ware);
		Put(R, "countAfterRelearn", FromInt((long long)K.Facts.size()));
		Put(R, "consistentAfterRelearn", FromInt((long long)K.CheckClaim(Ware)));
		K.Learn(Fact("player", "owes_d1", "forty"));
		Put(R, "countAfterSecondTopic", FromInt((long long)K.Facts.size()));
		Put(R, "toString", Escape(Fact("PLAYER", "Location_D2_Evening", "WAREHOUSE").ToString()));
		Put(R, "sameTopic", FromBool(Home.SameTopic(Ware)));
		Put(R, "sameTopicOther", FromBool(Home.SameTopic(Fact("player", "owes_d1", "forty"))));
	}

	inline void ScenarioSummaries(Readings& R)
	{
		// THE LEAK GUARD ON A REAL MILL. Three rumours, and only the two that
		// SAY the word out loud count; the possessive is a leak and the
		// plural is a different word.
		GossipMill Mill(std::make_shared<SocialGraph>());
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "a_d1", "x"),
		             "Mitch says it was player, and came to say so", false, GameTime(1, 12, 0), 1.0);
		Mill.Witness("w1", Fact("player", "b_d1", "x"),
		             "two players were there", false, GameTime(1, 12, 0), 1.0);
		Mill.Witness("w1", Fact("player", "c_d1", "x"),
		             "it was the player's coat", false, GameTime(1, 12, 0), 1.0);
		Put(R, "sayingPlayer", FromInt(Mill.SummariesSaying("player")));
		Put(R, "sayingNovak", FromInt(Mill.SummariesSaying("novak")));
		Put(R, "sayingEmpty", FromInt(Mill.SummariesSaying("")));
		Put(R, "rumors", FromInt((long long)Mill.Get("w1")->Rumors.size()));
	}

	// THE RUMOUR HALF OF THE SAVE, AND IT IS JSON RATHER THAN MARKDOWN.
	//
	// ScenarioSaveReload above pins a MEMORY surviving a save, and the save
	// format there is the markdown, because the C#'s own summary says NPC
	// memories persist separately and are not in the save file. A RUMOUR is
	// not in that markdown. It lives in the GossipMill and the mill goes into
	// the save FILE, under "agents", as JSON - a different format, a
	// different parser, and a different set of ways to lose something. Until
	// this scenario existed the port could not read a save at all.
	//
	// THE BYTES ARE THE C#'s, NOT MINE, and that is the whole point of the
	// saveFixture row below. The port cannot CAPTURE - there is no writer
	// here and there does not need to be - so if it restored from a fixture
	// it had written itself the comparison would prove only that the port
	// agrees with the port. This literal is what SaveCodec.Capture really
	// wrote, emitted by the C# as its own row, so the two engines are
	// demonstrably reading the same text before either of them reads it.
	inline void ScenarioGossipRestore(Readings& R)
	{
		static const std::string Fixture =
			"{\"version\":2,\"day\":3,\"hour\":9,\"minute\":0,\"clean\":0,\"dirty\":0"
			  ",\"washed\":0,\"patience\":1,\"exposedStreak\":0,\"jobsDone\":0,\"job"
			  "sMissed\":0,\"missedNights\":[],\"doneNights\":[],\"daysClosed\":0,"
			  "\"verdict\":\"Ongoing\",\"verdictReason\":\"\",\"openMode\":false,\"out"
			  "fitCutOff\":false,\"fallPending\":false,\"falls\":0,\"extra\":{},\"k"
			  "nowledge\":[],\"secrets\":[],\"beats\":[],\"debts\":[],\"discredited"
			  "\":[],\"agents\":[{\"id\":\"w1\",\"loyalty\":0.375,\"leashed\":true,\"su"
			  "spicion\":0,\"suppressed\":[\"player|owes_money_d1\"],\"rumors\":[{"
			  "\"subj\":\"player\",\"pred\":\"broke_window_d2\",\"val\":\"yes\",\"origin"
			  "\":\"w1\",\"summary\":\"I saw him put the window in at the Parade\""
			  ",\"conf\":0.95,\"hops\":0,\"sensitive\":false,\"indelible\":false},{"
			  "\"subj\":\"player\",\"pred\":\"owes_money_d1\",\"val\":\"yes\",\"origin\":"
			  "\"w1\",\"summary\":\"they say he is behind with Rita\",\"conf\":0.4,"
			  "\"hops\":0,\"sensitive\":true,\"indelible\":false}],\"facts\":[{\"sub"
			  "j\":\"player\",\"pred\":\"broke_window_d2\",\"val\":\"yes\"}]},{\"id\":\"n"
			  "1\",\"loyalty\":0.5,\"leashed\":false,\"suspicion\":0,\"suppressed\":"
			  "[],\"rumors\":[],\"facts\":[]}]}";

		// THE RESTART, MODELLED HONESTLY: a mill built from the authoring
		// with none of the play in it, and the save laid over the top. That
		// is what a restart is. Restoring into the mill that already holds
		// the rumours would prove nothing whatever.
		GossipMill Mill(std::make_shared<SocialGraph>());
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n1", "the barmaid",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "night"));
		Put(R, "rumorsBeforeRestore", FromInt((long long)Mill.Get("w1")->Rumors.size()));
		Put(R, "saveFixture", Escape(Fixture));

		Save::RestoreMillAgents(Fixture, Mill);

		GossiperPtr W = Mill.Get("w1");
		Put(R, "rumorsAfter", FromInt((long long)W->Rumors.size()));
		Put(R, "loyalty", FromDouble(W->Loyalty));
		Put(R, "leashed", FromBool(W->Leashed));
		Put(R, "suppressedCount", FromInt((long long)W->Suppressed.size()));
		Put(R, "factsAfter", FromInt(W->Knowledge ? (long long)W->Knowledge->Facts.size() : 0));
		for (std::vector<RumorPtr>::size_type I = 0; I < W->Rumors.size(); ++I)
		{
			const RumorPtr& Rm = W->Rumors[I];
			const std::string K = FromInt((long long)I);
			Put(R, "subj" + K, Escape(Rm->Content.Subject));
			Put(R, "pred" + K, Escape(Rm->Content.Predicate));
			Put(R, "val" + K, Escape(Rm->Content.Value));
			Put(R, "conf" + K, FromDouble(Rm->Confidence));
			Put(R, "hops" + K, FromInt((long long)Rm->Hops));
			Put(R, "sensitive" + K, FromBool(Rm->Sensitive));
			Put(R, "indelible" + K, FromBool(Rm->Indelible));
			Put(R, "summary" + K, Escape(Rm->Summary));
			Put(R, "origin" + K, Escape(Rm->OriginId));
		}

		// REJECTING HALF, AND IT IS THE HALF SaveChaos FOUND FROM THE OTHER
		// END. A rumour record with no "subj" is dropped whole, because a
		// fact with no subject is not a fact - the C# cannot build one from a
		// null and refuses; in C++ a std::string cannot BE null, so the
		// missing key has to be caught in the codec or the refusal would
		// vanish in translation and a belief about nobody would walk into a
		// conversation. An agent id this build never authored is skipped
		// rather than invented.
		static const std::string Junk =
			"{\"agents\":["
			"{\"id\":\"w1\",\"loyalty\":0.5,\"leashed\":false,\"suspicion\":0,"
			"\"suppressed\":[],\"rumors\":["
			"{\"pred\":\"p\",\"val\":\"v\",\"conf\":0.5,\"hops\":1},"
			"{\"subj\":\"player\",\"pred\":\"kept\",\"val\":\"yes\",\"conf\":0.25,\"hops\":2}"
			"],\"facts\":[]},"
			"{\"id\":\"nobody_authored_this\",\"loyalty\":0.9,\"rumors\":[]}"
			"]}";
		GossipMill JunkMill(std::make_shared<SocialGraph>());
		JunkMill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Save::RestoreMillAgents(Junk, JunkMill);
		GossiperPtr J = JunkMill.Get("w1");
		Put(R, "junkRumors", FromInt((long long)J->Rumors.size()));
		if (!J->Rumors.empty())
		{
			Put(R, "junkKeptPred", Escape(J->Rumors[0]->Content.Predicate));
			Put(R, "junkKeptConf", FromDouble(J->Rumors[0]->Confidence));
		}
		// THE SAME FOUR CASES, AND THE SAME BYTES. See the C# side for why
		// each record is here; the short version is that MiniJson's helpers
		// are stricter than JSON and a reader that asks only "is there
		// text?" disagrees with the engine about all four.
		static const std::string Strict =
			"{\"agents\":[{\"id\":\"w1\",\"loyalty\":0.25,\"leashed\""
			  ":1,\"suspicion\":0,\"suppressed\":[\"kept|topic\"],\"rumors"
			  "\":[{\"subj\":null,\"pred\":\"p\",\"val\":\"v\",\"conf\":0.9"
			  ",\"hops\":1},{\"subj\":5,\"pred\":\"p\",\"val\":\"v\",\"conf"
			  "\":0.9,\"hops\":1},{\"subj\":\"\",\"pred\":\"empty\",\"val\""
			  ":\"v\",\"conf\":0.8,\"hops\":3,\"sensitive\":true},{\"subj\""
			  ":\"player\",\"pred\":\"flagged\",\"val\":\"v\",\"conf\":0.7,"
			  "\"hops\":0,\"indelible\":1,\"sensitive\":\"true\"}],\"facts"
			  "\":[]}]}";
		GossipMill StrictMill(std::make_shared<SocialGraph>());
		StrictMill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Save::RestoreMillAgents(Strict, StrictMill);
		GossiperPtr SM = StrictMill.Get("w1");
		Put(R, "strictFixture", Escape(Strict));
		Put(R, "strictRumors", FromInt((long long)SM->Rumors.size()));
		Put(R, "strictLoyalty", FromDouble(SM->Loyalty));
		Put(R, "strictLeashed", FromBool(SM->Leashed));
		Put(R, "strictSuppressed", FromInt((long long)SM->Suppressed.size()));
		for (std::vector<RumorPtr>::size_type I = 0; I < SM->Rumors.size(); ++I)
		{
			const std::string K = FromInt((long long)I);
			Put(R, "strictPred" + K, Escape(SM->Rumors[I]->Content.Predicate));
			Put(R, "strictSubjLen" + K,
				FromInt((long long)SM->Rumors[I]->Content.Subject.size()));
			Put(R, "strictConf" + K, FromDouble(SM->Rumors[I]->Confidence));
			Put(R, "strictSensitive" + K, FromBool(SM->Rumors[I]->Sensitive));
			Put(R, "strictIndelible" + K, FromBool(SM->Rumors[I]->Indelible));
		}

		Put(R, "junkFixture", Escape(Junk));

		// THE WHOLE ROUND TRIP: SAVE, RESTART, RELOAD - with THIS engine's
		// writer. Everything above pins reading a save the C# wrote; this
		// pins writing one and reading it back, which is what a restart
		// actually is and what the probe needs before it can perform one.
		//
		// A MATCH HERE IS THE TWO ENGINES AGREEING ABOUT A FILE ONE OF THEM
		// NEVER SAW. The C# captures with its own codec and restores with
		// its own; this captures with CaptureMillAgents and restores with
		// RestoreMillAgents; if either writer loses something the other
		// keeps, the rows below part company.
		const std::string ReSaved = Save::CaptureMillAgents(Mill);
		GossipMill Restarted(std::make_shared<SocialGraph>());
		Restarted.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Restarted.Add(std::make_shared<Gossiper>("n1", "the barmaid",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "night"));
		Save::RestoreMillAgents(ReSaved, Restarted);
		GossiperPtr RS = Restarted.Get("w1");
		Put(R, "rtRumors", FromInt((long long)RS->Rumors.size()));
		Put(R, "rtLoyalty", FromDouble(RS->Loyalty));
		Put(R, "rtLeashed", FromBool(RS->Leashed));
		Put(R, "rtSuppressed", FromInt((long long)RS->Suppressed.size()));
		Put(R, "rtFacts", FromInt(RS->Knowledge ? (long long)RS->Knowledge->Facts.size() : 0));
		for (std::vector<RumorPtr>::size_type I = 0; I < RS->Rumors.size(); ++I)
		{
			const std::string K = FromInt((long long)I);
			Put(R, "rtPred" + K, Escape(RS->Rumors[I]->Content.Predicate));
			Put(R, "rtConf" + K, FromDouble(RS->Rumors[I]->Confidence));
			Put(R, "rtHops" + K, FromInt((long long)RS->Rumors[I]->Hops));
			Put(R, "rtSensitive" + K, FromBool(RS->Rumors[I]->Sensitive));
			Put(R, "rtSummary" + K, Escape(RS->Rumors[I]->Summary));
		}
		// AND THE CONTROL CAME THROUGH AS A CONTROL.
		Put(R, "rtControlRumors", FromInt((long long)Restarted.Get("n1")->Rumors.size()));

		// THE SAME CASES AND THE SAME BYTES. See the C# side for what each
		// record is for; every one of them was a real disagreement between
		// the two engines reading the same file, found by somebody who had
		// not seen how this was written.
		static const std::string Review =
			"{\"agents\":[{\"id\":\"w1\",\"loyalty\":0.1,\"loyalty\":0."
			  "9,\"suppressed\":[\"same\",\"same\",\"other\"],\"rumors\":"
			  "[{\"subj\":\"player\",\"pred\":\"boolconf\",\"val\":\"v\","
			  "\"conf\":true,\"hops\":0},{\"subj\":\"player\",\"pred\":\""
			  "quotedhops\",\"val\":\"v\",\"conf\":0.5,\"hops\":\"2\"},{"
			  "\"subj\":\"player\",\"pred\":\"hugehops\",\"val\":\"v\",\""
			  "conf\":0.5,\"hops\":1e18},{\"subj\":\"player\",\"pred\":\""
			  "escapes\",\"val\":\"v\",\"conf\":0.5,\"hops\":0,\"summary"
			  "\":\"\\r\\n\\t\\b\\f\\\\\\\"\\/\\u0041\"}],\"facts\":[]}]}";
		GossipMill ReviewMill(std::make_shared<SocialGraph>());
		ReviewMill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Save::RestoreMillAgents(Review, ReviewMill);
		GossiperPtr RV = ReviewMill.Get("w1");
		Put(R, "reviewFixture", Escape(Review));
		Put(R, "reviewLoyalty", FromDouble(RV->Loyalty));
		Put(R, "reviewSuppressed", FromInt((long long)RV->Suppressed.size()));
		Put(R, "reviewRumors", FromInt((long long)RV->Rumors.size()));
		for (std::vector<RumorPtr>::size_type I = 0; I < RV->Rumors.size(); ++I)
		{
			const std::string K = RV->Rumors[I]->Content.Predicate;
			Put(R, "review_" + K + "_conf", FromDouble(RV->Rumors[I]->Confidence));
			Put(R, "review_" + K + "_hops", FromInt((long long)RV->Rumors[I]->Hops));
		}
		// BY CODE POINT, because the table's escaping drops a carriage
		// return and would have hidden the difference this pins.
		{
			RumorPtr Esc;
			for (std::vector<RumorPtr>::size_type I = 0; I < RV->Rumors.size(); ++I)
			{
				if (RV->Rumors[I]->Content.Predicate == "escapes") { Esc = RV->Rumors[I]; }
			}
			Put(R, "reviewSummaryLen",
				FromInt(Esc ? (long long)Esc->Summary.size() : -1));
			if (Esc)
			{
				for (std::string::size_type I = 0; I < Esc->Summary.size(); ++I)
				{
					Put(R, "reviewSummaryCp" + FromInt((long long)I),
						FromInt((long long)(unsigned char)Esc->Summary[I]));
				}
			}
		}

		// AND A BROKEN SAVE CHANGES NOTHING AT ALL.
		static const std::string Broken =
			"{\"agents\":[{\"id\":\"w1\",\"loyalty\":0.9,\"rumors\":[{"
			  "\"subj\":\"player\",\"pred\":\"fromthesave\",\"val\":\"v\""
			  ",\"conf\":0.9,\"hops\":0}]}],\"day\":01x}";
		GossipMill KeptMill(std::make_shared<SocialGraph>());
		KeptMill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		KeptMill.Witness("w1", Fact("player", "already_knew", "yes"),
		                 "she knew this before the load", false, GameTime(1, 9, 0), 0.8);
		KeptMill.Get("w1")->Loyalty = 0.42;
		Save::RestoreMillAgents(Broken, KeptMill);
		Put(R, "brokenFixture", Escape(Broken));
		Put(R, "brokenRumors", FromInt((long long)KeptMill.Get("w1")->Rumors.size()));
		Put(R, "brokenLoyalty", FromDouble(KeptMill.Get("w1")->Loyalty));
		Put(R, "brokenKeptPred", KeptMill.Get("w1")->Rumors.empty()
			? std::string("none")
			: Escape(KeptMill.Get("w1")->Rumors[0]->Content.Predicate));

		// A RESTORE REPLACES RATHER THAN APPENDS, which is the difference
		// between reloading a save and doubling every rumour in it - and
		// reloading is a thing a player does.
		Save::RestoreMillAgents(Fixture, Mill);
		Put(R, "restoreTwiceRumors", FromInt((long long)Mill.Get("w1")->Rumors.size()));
	}

	// THE SAVE, AND IT IS THE MARKDOWN. Every row here answers one the C#
	// emits in PerceptionGolden's own save_reload block; the two are written
	// from the same fixtures on purpose, because a round trip proved against
	// a fixture the port chose would prove only that the port agrees with
	// itself.
	inline void ScenarioSaveReload(Readings& R)
	{
		MemoryStore Before("w1");
		Before.Beliefs.push_back("the man in the coat is not to be trusted");
		Before.Beliefs.push_back("the Parade is quiet after six");
		Before.Append(MemoryEvent(GameTime(2, 19, 40), "observation", 0.62,
		                          "I saw him put the window in at the Parade"));
		Before.Append(MemoryEvent(GameTime(2, 19, 45), "heard", 0.36096,
		                          "the shopkeeper says his face is known if not his name"));
		Before.Append(MemoryEvent(GameTime(3, 8, 5), "reflection", 0.125,
		                          "  two lines\nbecome one  "));

		MemoryStore After("w1");
		After.LoadFrom(Before.ToMarkdown());

		Put(R, "eventsAfter", FromInt((long long)After.Events.size()));
		Put(R, "beliefsAfter", FromInt((long long)After.Beliefs.size()));
		Put(R, "belief0", After.Beliefs.empty() ? std::string("none")
		                                        : Escape(After.Beliefs[0]));
		Put(R, "line0", LineOf(After, 0));
		Put(R, "line1", LineOf(After, 1));
		Put(R, "line2", LineOf(After, 2));
		// THE ROUND TRIP IS NOT LOSSLESS AND THESE TWO ROWS SAY SO. ToLine
		// renders importance at two decimals, so 0.36096 goes to the file as
		// 0.36 and comes back as 0.36. That is the engine's behaviour, not a
		// defect to repair here, and a port that "fixed" it would disagree
		// with the C# on a rumour's confidence and nobody would see it.
		Put(R, "importanceBefore", Before.Events.size() > 1
		        ? FromDouble(Before.Events[1].Importance) : std::string("none"));
		Put(R, "importanceAfter", After.Events.size() > 1
		        ? FromDouble(After.Events[1].Importance) : std::string("none"));
		Put(R, "markdownIsStable", FromBool(After.ToMarkdown() == Before.ToMarkdown()));
		Put(R, "day0", After.Events.empty() ? std::string("none")
		                                    : FromInt(After.Events[0].Time.Day));
		Put(R, "hour0", After.Events.empty() ? std::string("none")
		                                     : FromInt(After.Events[0].Time.Hour));
		Put(R, "minute0", After.Events.empty() ? std::string("none")
		                                       : FromInt(After.Events[0].Time.Minute));
		Put(R, "text2", After.Events.size() > 2 ? Escape(After.Events[2].Text)
		                                        : std::string("none"));

		// REJECTING HALF: A FILE WITH RUBBISH IN IT STILL LOADS.
		const std::string JunkFixtureText =
			std::string("# Memory: w1\n\n## Beliefs" "\xC2\xA0" "\n")
			+ "- kept\n"
			+ "   - indented belief\n"
			+ "not a belief line\n"
			+ "\n## Events \n"
			+ "- [D2 19:40] (0.62|observation) kept one\n"
			+ "this is not an event line\n"
			+ "- [D2 19:41 (0.62|observation) no closing bracket\n"
			+ "- [D2 19:42] 0.62|observation) no opening paren\n"
			+ "- [D2 19:43] (0.62|observation no closing paren\n"
			+ "- [DX 19:44] (0.62|observation) bad time\n"
			+ "- [D2 19:45] (notanumber|observation) bad importance\n"
			+ "- [D2 19:46] (0.62|observation|extra) too many fields\n"
			+ "- [D2 19:48] :) (0.62|observation) smiley\n"
			+ "x [D2 19:49] (0.62|observation) no dash-bracket prefix\n"
			+ "- [ D2 19:50] (0.62|observation) space before the D\n"
			+ "- [D2 19:51] (NaN|heard) not a number but the C# takes it\n"
			+ "- [D-2147483648 0:0] (0.5|heard) the smallest int there is\n"
			+ "- [D2 19:47] (0.62|observation) kept two\n";
		MemoryStore Junk("w1");
		Junk.LoadFrom(JunkFixtureText);
		Put(R, "junkEvents", FromInt((long long)Junk.Events.size()));
		Put(R, "junkBeliefs", FromInt((long long)Junk.Beliefs.size()));
		for (std::vector<MemoryEvent>::size_type I = 0; I < Junk.Events.size(); ++I)
		{
			Put(R, "junkKept" + FromInt((long long)I), Escape(Junk.Events[I].Text));
			Put(R, "junkLine" + FromInt((long long)I), Escape(Junk.Events[I].ToLine()));
		}
		for (std::vector<std::string>::size_type I = 0; I < Junk.Beliefs.size(); ++I)
		{
			Put(R, "junkBelief" + FromInt((long long)I), Escape(Junk.Beliefs[I]));
		}
		// THE FIXTURE ITSELF IS A ROW, for the reason the C# block states: two
		// fixtures that drift apart while both stay green are two different
		// tests wearing one name.
		Put(R, "junkFixture", Escape(JunkFixtureText));

		MemoryStore Twice("w1");
		Twice.LoadFrom(Before.ToMarkdown());
		Twice.LoadFrom(Before.ToMarkdown());
		Put(R, "loadTwiceEvents", FromInt((long long)Twice.Events.size()));
		Put(R, "loadTwiceBeliefs", FromInt((long long)Twice.Beliefs.size()));
	}

	inline Readings Scenario(const std::string& Name)
	{
		Readings R;
		if      (Name == "mem_basic")             ScenarioMemBasic(R);
		else if (Name == "mem_permanent")         ScenarioMemPermanent(R);
		else if (Name == "gossip_crime")          ScenarioGossipCrime(R);
		else if (Name == "gossip_dropped")        ScenarioGossipDropped(R);
		else if (Name == "gossip_contradiction")  ScenarioGossipContradiction(R);
		else if (Name == "gossip_exposure")       ScenarioGossipExposure(R);
		else if (Name == "gossip_suppressed")     ScenarioGossipSuppressed(R);
		else if (Name == "gossip_leashed")        ScenarioGossipLeashed(R);
		else if (Name == "gossip_indelible")      ScenarioGossipIndelible(R);
		else if (Name == "gossip_indelible_floor")ScenarioGossipIndelibleFloor(R);
		else if (Name == "witness_upgrade")       ScenarioWitnessUpgrade(R);
		else if (Name == "observation_four")      ScenarioObservationFour(R);
		else if (Name == "knowledge")             ScenarioKnowledge(R);
		else if (Name == "summaries")             ScenarioSummaries(R);
		else if (Name == "save_reload")           ScenarioSaveReload(R);
		else if (Name == "gossip_restore")        ScenarioGossipRestore(R);
		return R;
	}

	// SCENARIOS THE PORT DOES NOT IMPLEMENT, NAMED ONCE, HERE, BECAUSE TWO
	// READERS CONSUME THIS TABLE AND THEY DISAGREED ABOUT THEM.
	//
	// ue-probe/tests/core-port-test.cpp fails on a row it cannot answer, and
	// carried its own copy of this list so the known hole could be skipped and
	// counted. The IN-ENGINE reader in LedgerProbe.cpp had no list at all: it
	// lumped every unanswerable row into one `Unknown` total, printed "N
	// row(s) named a function this build does not implement", and PASSED
	// ANYWAY, because its verdict only looked at mismatches. So the cheap
	// check was strict about holes and the expensive one was not, and a real
	// hole opening in the port would have gone red in one and green in the
	// other. One list, one meaning, both readers.
	//
	// THE LIST IS SELF-EXPIRING. Both readers assert that every name on it is
	// genuinely unanswerable by this build, so the day somebody ports
	// PlayerClaims the assertion goes red and the name must come off.
	inline const char* UnportedScenarios(int Index)
	{
		static const char* Names[] = { "claims", 0 };
		return Names[Index];
	}

	// AND THE ROWS THIS BUILD CANNOT ANSWER BECAUSE OF HOW IT IS COMPILED.
	//
	// FactNull's four rows need exceptions, and the Unreal module compiles
	// with them OFF - ruled in advance, in LedgerProbe.Build.cs, which says
	// what it costs: "the four FactNull rows stop being answered and count as
	// Unknown, which the run says in words". The container's binaries have
	// exceptions, so they answer all four; the engine cannot. That is a
	// difference between BUILDS of the same port rather than a hole in it,
	// which is why it is keyed to the compile flag and not to a name list.
	//
	// IT WAS TOLERATED SILENTLY UNTIL 2026-09-22, because the in-engine reader
	// counted unanswered rows and passed anyway. Now that an unanswered row
	// fails, the four have to be named here or the engine can never be green.
	// Named and counted is the honest shape; counted and ignored was not.
	inline bool IsUnanswerableByThisBuild(const std::string& Fn)
	{
#if defined(LEDGER_CORE_NO_EXCEPTIONS) && LEDGER_CORE_NO_EXCEPTIONS
		return Fn == "FactNull";
#else
		(void)Fn;
		return false;
#endif
	}

	inline bool IsUnportedScenario(const std::string& Name)
	{
		for (int I = 0; UnportedScenarios(I) != 0; ++I)
		{
			if (Name == UnportedScenarios(I)) { return true; }
		}
		return false;
	}

	inline const char* ScenarioNames(int Index)
	{
		static const char* Names[] = {
			"mem_basic", "mem_permanent", "gossip_crime", "gossip_dropped",
			"gossip_contradiction", "gossip_exposure", "gossip_suppressed",
			"gossip_leashed", "gossip_indelible", "gossip_indelible_floor",
			"witness_upgrade", "observation_four", "knowledge", "summaries",
			"save_reload", "gossip_restore", 0
		};
		return Names[Index];
	}

	// ---- one row in, one answer out ---------------------------------

	struct Answer
	{
		bool        Known;   // false means this build implements no such row
		std::string Got;     // the port's answer, escaped exactly as the table is
		Answer() : Known(false) {}
	};

	// THE PERCEPTION CONSTANTS, ANSWERED BY NAME. A constant that drifted
	// would otherwise only show up through whichever function happens to
	// read it, and "the radius is wrong" is a much worse bug report than
	// "AudibleDivisor is 8.5 here and 8.0 there".
	inline Answer PerceptionConst(const std::string& Name)
	{
		Answer A;
		A.Known = true;
		if      (Name == "NoticeSeconds")        A.Got = FromDouble(Perception::NoticeSeconds);
		else if (Name == "AmbientNight3am")      A.Got = FromDouble(Perception::AmbientNight3am);
		else if (Name == "AmbientDaytimeStreet") A.Got = FromDouble(Perception::AmbientDaytimeStreet);
		else if (Name == "LoudShout")            A.Got = FromDouble(Perception::LoudShout);
		else if (Name == "LoudBottleSmash")      A.Got = FromDouble(Perception::LoudBottleSmash);
		else if (Name == "WallAttenuation")      A.Got = FromDouble(Perception::WallAttenuation);
		else if (Name == "LoudRemark")           A.Got = FromDouble(Perception::LoudRemark);
		else if (Name == "AudibleBaseMetres")    A.Got = FromDouble(Perception::AudibleBaseMetres);
		else if (Name == "AudibleDivisor")       A.Got = FromDouble(Perception::AudibleDivisor);
		else if (Name == "AudibleCapMetres")     A.Got = FromDouble(Perception::AudibleCapMetres);
		else if (Name == "AlertFloorDrop")       A.Got = FromDouble(Perception::AlertFloorDrop);
		else A.Known = false;
		return A;
	}

	// Resolve's arguments, in the order the table writes them. Named once
	// here and once in Program.cs, and the two lists are the contract.
	//   1 loudness        2 criesOut       3 weaponDrawn   4 actorFled
	//   5 leavesBody      6 hadPrecursor   7 isAccident
	//   8 actorMetres     9 actorOffAxis  10 actorLight   11 actorOccluded
	//  12 victimMetres   13 victimOffAxis 14 victimLight  15 victimOccluded
	//  16 familiarity    17 actorHasMark  18 faceToward   19 ambientFloor
	//  20 alertness      21 secondsWatching  22 rungFloor 23 arrivedLater
	//  24 field          25 expected
	inline Answer ResolveRow(const std::vector<std::string>& F)
	{
		Answer A;
		if (F.size() < 26) return A;
		Deed Dd;
		Dd.EventId = "e1"; Dd.ActorId = "a1"; Dd.VictimId = "v1";
		Dd.Loudness = D(F[1]); Dd.VictimCriesOut = B(F[2]); Dd.WeaponDrawn = B(F[3]);
		Dd.ActorFled = B(F[4]); Dd.LeavesBody = B(F[5]); Dd.HadPrecursor = B(F[6]);
		Dd.IsAccident = B(F[7]);
		Vantage V;
		V.WitnessId = "w1";
		V.ToActor  = Sight::At(D(F[8]),  D(F[10]), D(F[9]),  B(F[11]));
		V.ToVictim = Sight::At(D(F[12]), D(F[14]), D(F[13]), B(F[15]));
		V.Familiarity = D(F[16]); V.ActorHasMark = B(F[17]); V.FaceToward = B(F[18]);
		V.AmbientFloor = D(F[19]); V.Alertness = D(F[20]); V.SecondsWatching = D(F[21]);
		V.RungFloor = I(F[22]); V.ArrivedLater = B(F[23]);

		const Observation O = Observe::Resolve(Dd, V);
		const std::string& Field = F[24];
		A.Known = true;
		if      (Field == "slots")         A.Got = FromInt((long long)(int)O.Slots);
		else if (Field == "rung")          A.Got = FromInt(O.Rung);
		else if (Field == "certainty")     A.Got = FromDouble(O.Certainty);
		else if (Field == "willingness")   A.Got = FromDouble(O.Willingness);
		else if (Field == "label")         A.Got = Escape(O.Label());
		else if (Field == "accused")       A.Got = Escape(O.AccusedId.empty() ? std::string("none") : O.AccusedId);
		else if (Field == "namesSomebody") A.Got = FromBool(O.NamesSomebody());
		// The two fields Resolve never writes, pinned at their defaults so a
		// constructor that stopped setting them would go red. The C# field is
		// Observation.Awareness; see the rename note in Observation.h.
		else if (Field == "awareness")     A.Got = FromInt((long long)O.AwarenessState);
		else if (Field == "retellings")    A.Got = FromInt(O.Retellings);
		else if (Field == "empty")         A.Got = FromBool(O.Empty());
		else if (Field == "witnessId")     A.Got = Escape(O.WitnessId);
		else if (Field == "eventId")       A.Got = Escape(O.EventId);
		else A.Known = false;
		return A;
	}

	inline Answer Evaluate(const std::vector<std::string>& F)
	{
		Answer A;
		if (F.size() < 3) return A;
		const std::string& Fn = F[0];

		// The vision half, ported first and answered here so that ONE
		// dispatcher covers the whole table.
		if (Fn == "MotionFactor" && F.size() >= 3)
		{
			A.Known = true; A.Got = FromDouble(Perception::MotionFactor(D(F[1])));
		}
		else if (Fn == "ConeWeight" && F.size() >= 3)
		{
			A.Known = true; A.Got = FromDouble(Perception::ConeWeight(D(F[1])));
		}
		else if (Fn == "LightFactor" && F.size() >= 3)
		{
			A.Known = true; A.Got = FromDouble(Perception::LightFactor(D(F[1])));
		}
		else if (Fn == "FacingIsReadable" && F.size() >= 4)
		{
			A.Known = true; A.Got = FromBool(Perception::FacingIsReadable(D(F[1]), D(F[2])));
		}
		else if (Fn == "InSight" && F.size() >= 7)
		{
			A.Known = true;
			A.Got = FromBool(Perception::InSight(D(F[1]), D(F[2]), D(F[3]), B(F[4]), D(F[5])));
		}
		else if (Fn == "IdRung" && F.size() >= 7)
		{
			A.Known = true;
			A.Got = FromInt(Perception::IdRung(D(F[1]), D(F[2]), D(F[3]), B(F[4]), B(F[5])));
		}
		else if (Fn == "SymmetryPredictsSeen" && F.size() >= 7)
		{
			A.Known = true;
			A.Got = FromBool(Perception::SymmetryPredictsSeen(D(F[1]), D(F[2]), D(F[3]), D(F[4]), B(F[5])));
		}
		// The hearing half.
		else if (Fn == "PerceptionConst" && F.size() >= 3)
		{
			A = PerceptionConst(F[1]);
		}
		else if (Fn == "AudibleRadius" && F.size() >= 5)
		{
			A.Known = true;
			A.Got = FromDouble(Perception::AudibleRadius(D(F[1]), D(F[2]), B(F[3])));
		}
		else if (Fn == "EffectiveFloor" && F.size() >= 4)
		{
			A.Known = true;
			A.Got = FromDouble(Perception::EffectiveFloor(D(F[1]), D(F[2])));
		}
		else if (Fn == "Heard" && F.size() >= 7)
		{
			A.Known = true;
			A.Got = FromBool(Perception::Heard(D(F[1]), D(F[2]), D(F[3]), B(F[4]), D(F[5])));
		}
		// Observation.
		else if (Fn == "Label" && F.size() >= 3)
		{
			Observation O;
			O.Slots = (Slot)I(F[1]);
			A.Known = true; A.Got = Escape(O.Label());
		}
		else if (Fn == "CertaintyFor" && F.size() >= 6)
		{
			A.Known = true;
			A.Got = FromDouble(Observe::CertaintyFor((Slot)I(F[1]), I(F[2]), B(F[3]), B(F[4])));
		}
		else if (Fn == "Resolve")
		{
			A = ResolveRow(F);
		}
		// GameTime.
		else if (Fn == "GameTime" && F.size() >= 6)
		{
			const GameTime T(I(F[1]), I(F[2]), I(F[3]));
			A.Known = true;
			if      (F[4] == "toString")     A.Got = Escape(T.ToString());
			else if (F[4] == "totalMinutes") A.Got = FromInt(T.TotalMinutes());
			else A.Known = false;
		}
		// MemoryEvent.
		else if (Fn == "MemoryLine" && F.size() >= 8)
		{
			const MemoryEvent E(GameTime(I(F[1]), I(F[2]), I(F[3])), Unescape(F[4]),
			                    D(F[5]), Unescape(F[6]));
			A.Known = true;
			A.Got = Escape(E.ToLine());
		}
		else if (Fn == "TwoDecimals" && F.size() >= 3)
		{
			A.Known = true; A.Got = Escape(FormatTwoDecimals(D(F[1])));
		}
		// Suspicion.
		else if (Fn == "FactNull" && F.size() >= 3)
		{
#if !LEDGER_CORE_EXCEPTIONS
			// COMPILED OUT, NOT SILENTLY PASSED. Provoking the refusal needs
			// a catch, and this module was built without exceptions
			// (Suspicion.h says why and how it got switched on). The four
			// rows then report UNKNOWN, which the done line counts, and the
			// verdict names the reason so an unanswered row cannot read as an
			// answered one. The container build always has exceptions, so the
			// four rows are proved there either way.
			A.Known = false;
			return A;
#else
			// THE REFUSAL, PROVOKED. The C# throws ArgumentNullException with
			// the argument's name; this throws std::invalid_argument with the
			// same name, and the row compares the NAME rather than the type,
			// because the name is the part that was worth keeping.
			const char* S = F[1] == "subject"   ? 0 : "player";
			const char* P = F[1] == "predicate" ? 0 : "broke_window_d1";
			const char* V = F[1] == "value"     ? 0 : "east_parade_glass0";
			A.Known = true;
			try
			{
				const Fact Made(S, P, V);
				A.Got = Escape(Made.ToString());
			}
			catch (const std::invalid_argument& E)
			{
				A.Got = std::string("threw/") + E.what();
			}
#endif
		}
		else if (Fn == "SaysWord" && F.size() >= 4)
		{
			A.Known = true;
			A.Got = FromBool(GossipMill::SaysWord(Unescape(F[1]), Unescape(F[2])));
		}
		else if (Fn == "IsWordChar" && F.size() >= 3)
		{
			const std::string C = Unescape(F[1]);
			A.Known = true;
			A.Got = FromBool(!C.empty() && GossipMill::IsWordChar(C[0]));
		}
		// The stateful ones.
		else if (Fn == "Scenario" && F.size() >= 4)
		{
			const Readings Rd = Scenario(F[1]);
			for (Readings::size_type Ix = 0; Ix < Rd.size(); ++Ix)
			{
				if (Rd[Ix].first == F[2]) { A.Known = true; A.Got = Rd[Ix].second; return A; }
			}
			// A key the scenario does not produce is UNKNOWN rather than
			// wrong: the two answers have different fixes, and a missing key
			// counted as a mismatch would read as a broken model.
			A.Known = false;
		}
		return A;
	}
}
}
