// GENERATED by tools/port_own_lines.py from ledger/Assets/Scripts/Core/OwnLines.cs;
// never edited by hand (run the tool; --check says when it is stale).
//
// THE STREET'S NAMED PEOPLE IN THEIR OWN WORDS (the town's U2, 30 September):
// a named person's own lines for a bank, taken before the shared bank's, kept
// by the remark ledger as "bank@id" so the no-repeat rule runs over theirs.
// StreetVoice.h's Own() reads this. Checked against PerceptionGolden's
// EmitOwnLines rows (OwnLine, OwnAmbient, OwnRecognition, OwnFaint, OwnFresh).
//
// NO UNREAL TYPE IS IN THIS FILE, as every file of the port.
#pragma once

#include <string>

namespace LedgerCore
{
	namespace OwnLines
	{
		struct Bank { const char* Who; const char* Name; const char* const* Lines; int Count; };

		// rocco, ambient/open/ordinary
		static const char* const k0[32] = {
			"How's the world treating you, friend?",
			"Keeping all right, friend?",
			"Weather can't make its mind up.",
			"Wind's round to the east. Feel that.",
			"Fish van was late again.",
			"Still going, then?",
			"How's the back?",
			"Not seen you on the street for a bit.",
			"Kept you busy, have they?",
			"Quiet on the rank today.",
			"Taking it steady, friend?",
			"Did you get that sorted, in the end?",
			"Anything going cheap your end?",
			"Grey old day, this.",
			"Smell of fish never leaves this street, does it?",
			"Not much in the paper. Never is.",
			"Bearing up, friend?",
			"Cold enough for you, friend?",
			"Your feet holding up?",
			"These boots have done some miles on that rank.",
			"Looking better than last week, friend.",
			"Anything doing your end?",
			"They've still not fixed that lamp by the gate.",
			"Getting by, are you?",
			"Days are drawing in now, friend.",
			"Water's brown as tea today.",
			"You get your letter about the poll tax?",
			"Gulls are loud today. Weather coming.",
			"Keeping out of trouble?",
			"You all right? You look done in.",
			"Stop a minute, friend. How's things?",
			"You'll want your big coat soon.",
		};
		// rocco, ambient/reply/ordinary
		static const char* const k1[10] = {
			"Same as ever, friend.",
			"Can't grumble. Wouldn't do any good.",
			"Getting by, friend. Getting by.",
			"Not so bad. Feet are killing me.",
			"Could be worse. Thirty years on the quay taught me that.",
			"Aye, well. You know how it is.",
			"I'll live, friend.",
			"Don't start me off, friend.",
			"Ask me when I've sat down.",
			"One day at a time, friend.",
		};
		// rocco, ambient/open/night
		static const char* const k2[14] = {
			"You're out late, friend.",
			"Rank's dead. Not had a fare in an hour.",
			"Cold's come down now, hasn't it.",
			"Quiet as the grave tonight.",
			"Last hour, then I'm off.",
			"Only us daft enough to be out, friend.",
			"Mind the kerb. It's black as pitch down there.",
			"You want to get yourself home. It's bitter.",
			"Street's a different place once it's dark.",
			"I'll give it another hour, then I'm off.",
			"Hear that? Just the water.",
			"Not a soul about. I like it like this.",
			"You'll catch your death out here.",
			"Long shift, friend?",
		};
		// rocco, ambient/reply/night
		static const char* const k3[6] = {
			"Someone's got to watch the gate.",
			"Nearly done, friend. Nearly.",
			"Nights are the easy bit. Nobody wants owt.",
			"I don't sleep much these days anyway.",
			"Go on, get yourself in.",
			"Aye. Mind how you go.",
		};
		// rocco, ambient/open/slump
		static const char* const k4[6] = {
			"Three fares. That's the lot. Three.",
			"Street's dead since the docks went.",
			"Nobody's got the money for a cab these days.",
			"Cab's sat on that rank like it's parked for good.",
			"I've seen quiet, friend, but not like this.",
			"Bus shelter's busier than the rank.",
		};
		// rocco, ambient/reply/slump
		static const char* const k5[4] = {
			"Docks went and took the street with them.",
			"Somebody's making money. It's not round here.",
			"Same on the rank. Nobody's paying.",
			"I've seen it come and go. It comes back.",
		};
		// rocco, ambient/open/prices
		static const char* const k6[5] = {
			"Tea's gone up again at the caff.",
			"You seen what they want for a loaf now?",
			"Rent's up again. Letter came, bold as you like.",
			"Everything's dearer and nobody's wages are.",
			"Gas bill came. I had to sit down.",
		};
		// rocco, ambient/reply/prices
		static const char* const k7[3] = {
			"Don't. I've stopped looking.",
			"Same everywhere, friend.",
			"I go without, mostly. Easier.",
		};
		// rocco, ambient/open/injured
		static const char* const k8[3] = {
			"Don't ask. I walked into something.",
			"Took a knock. It's nothing.",
			"I'm all right. Don't fuss.",
		};
		// rocco, ambient/reply/injured
		static const char* const k9[3] = {
			"Seen that go bad on the quay. Mind it.",
			"Casualty'll see you. It's only a wait.",
			"Sit down a minute. The rank'll keep.",
		};
		// rocco, ambient/open/feud
		static const char* const k10[3] = {
			"I've nothing to say to you. Go on.",
			"You know where I stand. Keep walking.",
			"Say your piece or shift.",
		};
		// rocco, ambient/reply/feud
		static const char* const k11[3] = {
			"Suit yourself, friend.",
			"I'll remember that.",
			"I'm not the one stood there scowling.",
		};
		// rocco, ambient/open/justnow/glass
		static const char* const k12[2] = {
			"That's glass. That's a window, that.",
			"Hear that? Somebody's window.",
		};
		// rocco, ambient/open/justnow/shout
		static const char* const k13[2] = {
			"Who's that bawling?",
			"Somebody's shouting down there.",
		};
		// rocco, ambient/open/justnow/crash
		static const char* const k14[2] = {
			"What's come down?",
			"That was a crash, that.",
		};
		// rocco, ambient/open/justnow/noise
		static const char* const k15[2] = {
			"What was that?",
			"Hang on. Something's up.",
		};
		// rocco, ambient/reply/justnow
		static const char* const k16[3] = {
			"I'll not go looking. Not for nowt.",
			"Leave it be. It's not ours.",
			"Leave it. Somebody'll ring.",
		};
		// rocco, ambient/open/settling
		static const char* const k17[3] = {
			"Gone quiet again.",
			"Whatever it was, it's done.",
			"Whole street'll know by tomorrow.",
		};
		// rocco, ambient/reply/settling
		static const char* const k18[3] = {
			"Let it settle, friend.",
			"Somebody saw. Somebody always does.",
			"Best not to wonder, friend.",
		};
		// rocco, recognition/ordinary
		static const char* const k19[6] = {
			"Boss.",
			"All right. Rank's quiet.",
			"Boss. Kettle's on in the office.",
			"Cold one, boss. Mind how you go.",
			"Anything you want watching, boss?",
			"Quiet day. Mostly.",
		};
		// rocco, recognition/sensitive
		static const char* const k20[4] = {
			"Your name's going round, boss. Just so you know.",
			"People are talking. I don't join in.",
			"Keep your head down a day or two, boss.",
			"Heard a thing or two. It'll keep.",
		};
		// rocco, recognition/confronts
		static const char* const k21[2] = {
			"A word, boss. Not out here.",
			"We need to talk, you and me.",
		};
		// rocco, recognition/refuses
		static const char* const k22[2] = {
			"Not today, boss. Ask somebody else.",
			"I've nothing for you.",
		};
		// rocco, recognition/avoids
		static const char* const k23[3] = {
			"Boss.",
			"Busy, boss. After.",
			"Another time, boss.",
		};
		// rocco, recognition/taken-saw
		static const char* const k24[2] = {
			"Saw them put you in the car, boss. I kept the rank going.",
			"You're out, then. Saw them take you off.",
		};
		// rocco, recognition/taken-heard
		static const char* const k25[2] = {
			"Heard the police had you in, boss.",
			"They say you were down the station.",
		};
		// rocco, recognition/police-asked
		static const char* const k26[2] = {
			"Ellis was at me about you, boss. Wanted you to hear it from me.",
			"Detective stopped me about you, boss. You'll want to hear what she asked.",
		};
		// rocco, recognition/police-heard
		static const char* const k27[2] = {
			"Heard a detective's been asking round about you, boss.",
			"Police are asking about you, so they say.",
		};
		// rocco, recognition/arrival-saw
		static const char* const k28[2] = {
			"You'll be Mickey's nephew. Ron. I keep the rank.",
			"Saw you come in with your case. Mickey's nephew, is it?",
		};
		// rocco, recognition/arrival-heard
		static const char* const k29[2] = {
			"You'll be the new owner, then. Ron. The rank's mine, the door too.",
			"Heard Mickey's nephew had come. That'll be you, boss.",
		};
		// rocco, recognition/threat-told
		static const char* const k30[2] = {
			"I heard you, boss. I'm still stood here.",
			"Thirty years on the quay, boss. I've been told worse by better.",
		};
		// rocco, recognition/threat-heard
		static const char* const k31[2] = {
			"Word is you've been leaning on folk, boss. The street keeps count.",
			"Heard you've been threatening people. It gets round.",
		};
		// rocco, recognition/outfit-did
		static const char* const k32[2] = {
			"Heard you did Mickey's run. Watch yourself down there.",
			"Went all right, I hear, boss. Say nowt.",
		};
		// rocco, recognition/outfit-refused
		static const char* const k33[2] = {
			"I took your no down myself, boss. Mickey never sent one.",
			"They had it from me. They'll not forget it.",
		};
		// rocco, recognition/outfit-wounddown
		static const char* const k34[2] = {
			"That's Mickey's arrangement done with, boss. I took word down myself.",
			"They'll not be calling. That's finished.",
		};
		// rocco, recognition/outfit-noshow
		static const char* const k35[2] = {
			"Heard they waited on you at the landing, boss.",
			"You never went down. They'll have noticed.",
		};
		// rocco, recognition/week-winddown
		static const char* const k36[2] = {
			"Heard you're winding Mickey's down, boss. Just the cabs, then.",
			"Can't say I'm sorry, boss. Mickey's other business never did him any good.",
		};
		// rocco, recognition/week-takeover
		static const char* const k37[2] = {
			"Heard you're taking it all on. All of Mickey's.",
			"So you're the new Mickey, boss. We'll see.",
		};
		// rocco, recognition/week-wontsay
		static const char* const k38[2] = {
			"Sheila says you'll not tell her, boss. You'll not tell me either, I expect.",
			"Keeping it to yourself. Fair enough.",
		};
		// rocco, faint
		static const char* const k39[3] = {
			"That's the boss. Mickey's nephew.",
			"There's been talk about him. I'll not repeat it.",
			"He's all right. So far.",
		};
		// sam, recognition/sensitive
		static const char* const k40[3] = {
			"So listen. Your name's doing the rounds. I'm not saying where. Yet.",
			"Everybody's got a version of you going. Mine's the one worth having.",
			"There he is. You want to know what's being said, you know where I'll be.",
		};
		// sam, faint
		static const char* const k41[2] = {
			"Him? I had something on him. Can't have been worth much, I've forgot it.",
			"Don't look. That's him. Whisper going round a while back. Old news.",
		};
		// sam, recognition/police-asked
		static const char* const k42[2] = {
			"Ellis had me in a doorway over you. I said I'd seen nothing. I'm good at that.",
			"Your detective friend's been on at me. Didn't tell her much. Didn't know much, did I.",
		};
		// sam, recognition/taken-saw
		static const char* const k43[2] = {
			"Saw them stick you in the back of the panda. You're out quick. Who'd you know?",
			"Out already? Watched them drive you off. Thought that was the last of you.",
		};
		// sam, recognition/taken-heard
		static const char* const k44[2] = {
			"Hear you had a ride with the police. Free taxi, that. Nice for a cab man.",
			"They're saying the law lifted you. You're walking about, so it can't have been much.",
		};
		// sam, recognition/outfit-did
		static const char* const k45[2] = {
			"So you did Mickey's errand by the ferry. I'll not ask. I'd only have to forget it.",
			"Picked up the late run, they're saying. Nobody's heard it from me.",
		};
		// sam, recognition/outfit-refused
		static const char* const k46[2] = {
			"Turned them down, did you? Takes nerve, that. Or you don't know who they are.",
			"Word is you turned the ferry lot down. I'd walk the long way home for a bit.",
		};
		// sam, recognition/outfit-wounddown
		static const char* const k47[2] = {
			"Mickey's old arrangement's off, they say. There's people by the ferry not happy about that.",
			"Finished with the sideline, I hear. Clean hands. Doesn't pay, but there you go.",
		};
		// sam, recognition/outfit-noshow
		static const char* const k48[2] = {
			"You left them stood by the ferry half the night. They've been asking where you were.",
			"Never turned up, they're saying. I'd have a story ready if I were you.",
		};
		// sam, recognition/threat-told
		static const char* const k49[2] = {
			"Message received, mate. I've gone deaf and blind, me.",
			"No need to say it twice. I've forgot everything already.",
		};
		// sam, recognition/threat-heard
		static const char* const k50[2] = {
			"Leaning on folk now, are you? Not on me, I hope. I scare easy, me.",
			"Somebody's been told to keep shut, I hear. I keep shut for nothing, me.",
		};
		// sam, recognition/week-takeover
		static const char* const k51[2] = {
			"Mickey's whole lot, then? Big shoes, mate. Anything wants fetching, I'm your man.",
			"Taking the lot on, they're saying. You'll be needing friends. I'm cheap.",
		};
		// sam, recognition/week-winddown
		static const char* const k52[2] = {
			"Only the cabs from now on, I hear. Shame. I had ideas.",
			"Winding the other business up, they reckon. Safer. Duller, mind.",
		};
		// sam, recognition/week-wontsay
		static const char* const k53[2] = {
			"Not even telling Sheila, they say. You can tell me. I'll only tell people who pay.",
			"Keeping it under your hat. That's worth something, that, to the right buyer.",
		};
		// sam, recognition/refuses
		static const char* const k54[2] = {
			"I'm not dealing with you, mate. Bad for business.",
			"Your money's no good with me now. Nothing personal.",
		};
		// sam, recognition/confronts
		static const char* const k55[2] = {
			"Here. Word with you. What you did's got people asking me, and I don't like being asked.",
			"No, stop a minute. I've had nothing but grief over you.",
		};
		// emil, recognition/sensitive
		static const char* const k56[3] = {
			"I hear things, God help me. I don't hold any of them against a man.",
			"You look like a man carrying something. My door's open, any hour.",
			"There's a lot said about you. None of it's my business unless you make it so.",
		};
		// emil, faint
		static const char* const k57[2] = {
			"God keep him. There's been talk, I know. I'd not trouble with it.",
			"That's the young fella with the cabs. Whatever it was, I let it go by.",
		};
		// emil, recognition/police-asked
		static const char* const k58[2] = {
			"The detective was round asking about you. I said I see you about the street, which is the truth of it.",
			"That Ellis woman came to me about you. I've no stories to give her, and I said so.",
		};
		// emil, recognition/police-heard
		static const char* const k59[2] = {
			"The guards are asking after you, I'm told. The police, I mean. Old habit.",
			"If the police come to you, and you want somebody to stand beside you, say.",
		};
		// emil, recognition/taken-heard
		static const char* const k60[2] = {
			"I heard they took you in. I said a prayer, for what it's worth. It's not nothing.",
			"You're out, thank God. I hope they treated you decent.",
		};
		// emil, recognition/threat-told
		static const char* const k61[2] = {
			"Threats don't work on an old priest, son. I've nothing left anyone can take.",
			"I'll forget you said that. I'd rather you did too.",
		};
		// emil, recognition/threat-heard
		static const char* const k62[2] = {
			"Frightening people, they're saying. That's not the man I took you for.",
			"Fear buys you nothing in the end. I've watched men try.",
		};
		// emil, recognition/avoids
		static const char* const k63[2] = {
			"The chapel's waiting on me. Another time.",
			"Forgive me, I'm late for a call.",
		};
		// june, recognition/sensitive
		static const char* const k64[2] = {
			"Whatever you've got yourself into, I don't want to hear it. Well. Go on, then.",
			"You've got this street talking already. Took me years to get away from it.",
		};
		// june, recognition/police-heard
		static const char* const k65[2] = {
			"Police, now. I came back for a funeral, not this.",
			"Sort out whatever the police want before I go home, would you.",
		};
		// june, recognition/taken-heard
		static const char* const k66[2] = {
			"I'm not asking what the police wanted you for. I'm just saying I know.",
			"You get yourself arrested, and I'm the one getting looks in the street. Thanks.",
		};
		// june, recognition/avoids
		static const char* const k67[2] = {
			"Not now. I've a train to see about.",
			"I'm not stopping.",
		};

		inline const Bank* Banks(int& OutCount)
		{
			static const Bank All[68] = {
				{ "rocco", "ambient/open/ordinary", k0, 32 },
				{ "rocco", "ambient/reply/ordinary", k1, 10 },
				{ "rocco", "ambient/open/night", k2, 14 },
				{ "rocco", "ambient/reply/night", k3, 6 },
				{ "rocco", "ambient/open/slump", k4, 6 },
				{ "rocco", "ambient/reply/slump", k5, 4 },
				{ "rocco", "ambient/open/prices", k6, 5 },
				{ "rocco", "ambient/reply/prices", k7, 3 },
				{ "rocco", "ambient/open/injured", k8, 3 },
				{ "rocco", "ambient/reply/injured", k9, 3 },
				{ "rocco", "ambient/open/feud", k10, 3 },
				{ "rocco", "ambient/reply/feud", k11, 3 },
				{ "rocco", "ambient/open/justnow/glass", k12, 2 },
				{ "rocco", "ambient/open/justnow/shout", k13, 2 },
				{ "rocco", "ambient/open/justnow/crash", k14, 2 },
				{ "rocco", "ambient/open/justnow/noise", k15, 2 },
				{ "rocco", "ambient/reply/justnow", k16, 3 },
				{ "rocco", "ambient/open/settling", k17, 3 },
				{ "rocco", "ambient/reply/settling", k18, 3 },
				{ "rocco", "recognition/ordinary", k19, 6 },
				{ "rocco", "recognition/sensitive", k20, 4 },
				{ "rocco", "recognition/confronts", k21, 2 },
				{ "rocco", "recognition/refuses", k22, 2 },
				{ "rocco", "recognition/avoids", k23, 3 },
				{ "rocco", "recognition/taken-saw", k24, 2 },
				{ "rocco", "recognition/taken-heard", k25, 2 },
				{ "rocco", "recognition/police-asked", k26, 2 },
				{ "rocco", "recognition/police-heard", k27, 2 },
				{ "rocco", "recognition/arrival-saw", k28, 2 },
				{ "rocco", "recognition/arrival-heard", k29, 2 },
				{ "rocco", "recognition/threat-told", k30, 2 },
				{ "rocco", "recognition/threat-heard", k31, 2 },
				{ "rocco", "recognition/outfit-did", k32, 2 },
				{ "rocco", "recognition/outfit-refused", k33, 2 },
				{ "rocco", "recognition/outfit-wounddown", k34, 2 },
				{ "rocco", "recognition/outfit-noshow", k35, 2 },
				{ "rocco", "recognition/week-winddown", k36, 2 },
				{ "rocco", "recognition/week-takeover", k37, 2 },
				{ "rocco", "recognition/week-wontsay", k38, 2 },
				{ "rocco", "faint", k39, 3 },
				{ "sam", "recognition/sensitive", k40, 3 },
				{ "sam", "faint", k41, 2 },
				{ "sam", "recognition/police-asked", k42, 2 },
				{ "sam", "recognition/taken-saw", k43, 2 },
				{ "sam", "recognition/taken-heard", k44, 2 },
				{ "sam", "recognition/outfit-did", k45, 2 },
				{ "sam", "recognition/outfit-refused", k46, 2 },
				{ "sam", "recognition/outfit-wounddown", k47, 2 },
				{ "sam", "recognition/outfit-noshow", k48, 2 },
				{ "sam", "recognition/threat-told", k49, 2 },
				{ "sam", "recognition/threat-heard", k50, 2 },
				{ "sam", "recognition/week-takeover", k51, 2 },
				{ "sam", "recognition/week-winddown", k52, 2 },
				{ "sam", "recognition/week-wontsay", k53, 2 },
				{ "sam", "recognition/refuses", k54, 2 },
				{ "sam", "recognition/confronts", k55, 2 },
				{ "emil", "recognition/sensitive", k56, 3 },
				{ "emil", "faint", k57, 2 },
				{ "emil", "recognition/police-asked", k58, 2 },
				{ "emil", "recognition/police-heard", k59, 2 },
				{ "emil", "recognition/taken-heard", k60, 2 },
				{ "emil", "recognition/threat-told", k61, 2 },
				{ "emil", "recognition/threat-heard", k62, 2 },
				{ "emil", "recognition/avoids", k63, 2 },
				{ "june", "recognition/sensitive", k64, 2 },
				{ "june", "recognition/police-heard", k65, 2 },
				{ "june", "recognition/taken-heard", k66, 2 },
				{ "june", "recognition/avoids", k67, 2 },
			};
			OutCount = 68;
			return All;
		}

		/// HELD UNTIL JAFAR'S YES (the town's handover, 30 September: Ron's lines wait on his
		/// yes on the town's second page before he says them in the game). On for the port's
		/// checks; the game sets it at start (LedgerProbe.cpp: -OwnLines, or the golden test).
		inline bool& InUse() { static bool bInUse = true; return bInUse; }

		/// This person's own lines for the bank, and the name the ledger keeps
		/// them under ("bank@id"); false when they have none for it (OwnLines.For).
		inline bool For(const std::string& SpeakerId, const std::string& BankName,
		                std::string& OutBank, const char* const*& OutLines, int& OutCount)
		{
			if (!InUse()) return false;
			int N = 0;
			const Bank* All = Banks(N);
			for (int I = 0; I < N; ++I)
			{
				if (SpeakerId == All[I].Who && BankName == All[I].Name && All[I].Count > 0)
				{
					OutBank = BankName + "@" + SpeakerId;
					OutLines = All[I].Lines;
					OutCount = All[I].Count;
					return true;
				}
			}
			return false;
		}
	}
}
