#!/usr/bin/env python3
"""The named people's own street lines, from the C# Core into the C++ port.

    python tools/port_own_lines.py            # writes ue-probe/Source/LedgerProbe/Public/OwnLines.h
    python tools/port_own_lines.py --check    # 1 when the header no longer matches the C#
    python tools/port_own_lines.py --selftest

WHY, 30 September (the town's handover: "A NAMED PERSON'S OWN STREET LINES
(OwnLines.cs) ... please port it to StreetVoice.h"). Ron's 159 lines are the
sample, and every named character after Jafar's yes adds hundreds more; typed
across by hand they would drift a word at a time. So the header is made from
ledger/Assets/Scripts/Core/OwnLines.cs itself: every person, every bank, every
line, in the C#'s own order, and PerceptionGolden's OwnLine rows check each
line's text in both engines. The lines are plain ASCII with no escapes (this
refuses anything else rather than guess at a translation).
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "ledger", "Assets", "Scripts", "Core", "OwnLines.cs")
OUT = os.path.join(REPO, "ue-probe", "Source", "LedgerProbe", "Public", "OwnLines.h")

TOKEN = re.compile(r'\["([^"\\]+)"\]\s*=\s*new\s+Dictionary<string,\s*string\[\]>'
                   r'|\["([^"\\]+)"\]\s*=\s*new\s*\[\]'
                   r'|"((?:[^"\\]|\\.)*)"'
                   r'|(//[^\n]*)')


#: Forms the reader would misread, refused rather than guessed (the
#: independent check of 30 September: a verbatim string split in three, a
#: concatenation split in two, a block comment's cut line read as a line, a
#: bank declared as new string[] read as a line of the bank before it).
REFUSED = (("/*", "a block comment"), ('@"', "a verbatim string"), ('$"', "an interpolated string"),
           ("new string[]", "a bank declared as new string[]"))
CONCAT = re.compile(r'"\s*\+\s*"')
KEYED = re.compile(r'\["[^"]*"\]\s*=')


def parse(text):
    """{who: [(bank, [lines])]}, in the C#'s own order."""
    start = text.index("ByCast")
    end = text.index("public static (string bank, string[] lines)? For(")
    body = text[start:end]
    for form, what in REFUSED:
        if form in body:
            raise ValueError("OwnLines.cs holds %s (%s); this reader does not take it" % (what, form))
    if CONCAT.search(body):
        raise ValueError("OwnLines.cs joins two strings with +; this reader does not take it")
    known = len(re.findall(r'\["[^"\\]+"\]\s*=\s*new\s+Dictionary<string,\s*string\[\]>', body)) + len(re.findall(r'\["[^"\\]+"\]\s*=\s*new\s*\[\]', body))
    if len(KEYED.findall(body)) != known:
        raise ValueError("OwnLines.cs names a person or bank in a form this reader does not take")
    out, who, bank = {}, None, None
    for m in TOKEN.finditer(body):
        if m.group(4):
            continue                                    # a comment: its quotes are not lines
        if m.group(1):
            who = m.group(1)
            out[who] = []
        elif m.group(2):
            bank = m.group(2)
            if any(b == bank for b, _ in out[who]):
                raise ValueError("OwnLines.cs gives %s's bank %s twice" % (who, bank))
            out[who].append((bank, []))
        elif m.group(3) is not None:
            s = m.group(3)
            if "\\" in s or any(ord(c) < 32 or ord(c) > 126 for c in s):
                raise ValueError("a line with an escape or a non-ASCII character: %r" % s)
            if who is None or bank is None:
                raise ValueError("a line outside any person's bank: %r" % s)
            out[who][-1][1].append(s)
    return out


def header(people):
    L = []
    L.append("// GENERATED by tools/port_own_lines.py from ledger/Assets/Scripts/Core/OwnLines.cs;")
    L.append("// never edited by hand (run the tool; --check says when it is stale).")
    L.append("//")
    L.append("// THE STREET'S NAMED PEOPLE IN THEIR OWN WORDS (the town's U2, 30 September):")
    L.append("// a named person's own lines for a bank, taken before the shared bank's, kept")
    L.append("// by the remark ledger as \"bank@id\" so the no-repeat rule runs over theirs.")
    L.append("// StreetVoice.h's Own() reads this. Checked against PerceptionGolden's")
    L.append("// EmitOwnLines rows (OwnLine, OwnAmbient, OwnRecognition, OwnFaint, OwnFresh).")
    L.append("//")
    L.append("// NO UNREAL TYPE IS IN THIS FILE, as every file of the port.")
    L.append("#pragma once")
    L.append("")
    L.append("#include <string>")
    L.append("")
    L.append("namespace LedgerCore")
    L.append("{")
    L.append("\tnamespace OwnLines")
    L.append("\t{")
    L.append("\t\tstruct Bank { const char* Who; const char* Name; const char* const* Lines; int Count; };")
    L.append("")
    n = 0
    names = []
    for who in people:
        for bank, lines in people[who]:
            var = "k%d" % n
            names.append((who, bank, var, len(lines)))
            L.append("\t\t// %s, %s" % (who, bank))
            L.append("\t\tstatic const char* const %s[%d] = {" % (var, len(lines)))
            for s in lines:
                L.append('\t\t\t"%s",' % s)
            L.append("\t\t};")
            n += 1
    L.append("")
    L.append("\t\tinline const Bank* Banks(int& OutCount)")
    L.append("\t\t{")
    L.append("\t\t\tstatic const Bank All[%d] = {" % max(1, len(names)))
    for who, bank, var, count in names:
        L.append('\t\t\t\t{ "%s", "%s", %s, %d },' % (who, bank, var, count))
    L.append("\t\t\t};")
    L.append("\t\t\tOutCount = %d;" % len(names))
    L.append("\t\t\treturn All;")
    L.append("\t\t}")
    L.append("")
    L.append("\t\t/// HELD UNTIL JAFAR'S YES (the town's handover, 30 September: Ron's lines wait on his")
    L.append("\t\t/// yes on the town's second page before he says them in the game). On for the port's")
    L.append("\t\t/// checks; the game sets it at start (LedgerProbe.cpp: -OwnLines, or the golden test).")
    L.append("\t\tinline bool& InUse() { static bool bInUse = true; return bInUse; }")
    L.append("")
    L.append("\t\t/// This person's own lines for the bank, and the name the ledger keeps")
    L.append("\t\t/// them under (\"bank@id\"); false when they have none for it (OwnLines.For).")
    L.append("\t\tinline bool For(const std::string& SpeakerId, const std::string& BankName,")
    L.append("\t\t                std::string& OutBank, const char* const*& OutLines, int& OutCount)")
    L.append("\t\t{")
    L.append("\t\t\tif (!InUse()) return false;")
    L.append("\t\t\tint N = 0;")
    L.append("\t\t\tconst Bank* All = Banks(N);")
    L.append("\t\t\tfor (int I = 0; I < N; ++I)")
    L.append("\t\t\t{")
    L.append("\t\t\t\tif (SpeakerId == All[I].Who && BankName == All[I].Name && All[I].Count > 0)")
    L.append("\t\t\t\t{")
    L.append("\t\t\t\t\tOutBank = BankName + \"@\" + SpeakerId;")
    L.append("\t\t\t\t\tOutLines = All[I].Lines;")
    L.append("\t\t\t\t\tOutCount = All[I].Count;")
    L.append("\t\t\t\t\treturn true;")
    L.append("\t\t\t\t}")
    L.append("\t\t\t}")
    L.append("\t\t\treturn false;")
    L.append("\t\t}")
    L.append("\t}")
    L.append("}")
    return "\n".join(L) + "\n"


def made():
    return header(parse(open(SRC, encoding="utf-8").read()))


def selftest():
    ok = bad = 0

    def check(name, cond):
        nonlocal ok, bad
        if cond:
            ok += 1
        else:
            bad += 1
            print("port_own_lines selftest FAIL " + name)
    sample = ('ByCast = new Dictionary<string, Dictionary<string, string[]>> { ["rocco"] = new Dictionary<string, string[]> {\n'
              '// a comment "with quotes"\n ["faint"] = new[] { "One.", "Two, friend." }, ["x/y"] = new[] { "Three." } } };\n'
              'public static (string bank, string[] lines)? For(')
    p = parse(sample)
    check("people and banks in order", list(p) == ["rocco"] and [b for b, _ in p["rocco"]] == ["faint", "x/y"])
    check("the lines, comments skipped", p["rocco"][0][1] == ["One.", "Two, friend."])
    try:
        parse(sample.replace('"Three."', '"Th\\"ree."'))
        check("an escape is refused", False)
    except ValueError:
        check("an escape is refused", True)
    for form, why in (('"Two, friend." }, ["faint"] = new[] { "Again." }', "a bank given twice is refused"),
                     ('"Two, friend." /* cut: "Gone." */', "a block comment is refused"),
                     ('"Two, " + "friend."', "a joined string is refused"),
                     ('@"Two, friend."', "a verbatim string is refused"),
                     ('"Two, friend." }, ["z"] = new string[] { "Z." }', "new string[] is refused")):
        try:
            parse(sample.replace('"Two, friend."', form, 1))
            check(why, False)
        except ValueError:
            check(why, True)
    h = header(p)
    check("the header names each bank once", h.count('"faint",') == 1 and h.count('"x/y",') == 1)
    real = parse(open(SRC, encoding="utf-8").read())
    check("Ron's lines are all read (159 on 30 September, more later)", sum(len(l) for _, l in real.get("rocco", [])) >= 159)
    print("port_own_lines selftest: passed=%d/%d failed=%d" % (ok, ok + bad, bad))
    return 1 if bad else 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    text = made()
    if "--check" in sys.argv:
        same = os.path.exists(OUT) and open(OUT, encoding="utf-8").read() == text
        print("port_own_lines: %s" % ("the header matches the C#" if same else "STALE: run tools/port_own_lines.py"))
        sys.exit(0 if same else 1)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    people = parse(open(SRC, encoding="utf-8").read())
    print("port_own_lines: %s, %s" % (os.path.relpath(OUT, REPO).replace("\\", "/"),
          ", ".join("%s %d banks %d lines" % (w, len(b), sum(len(l) for _, l in b)) for w, b in people.items())))
